# 임베딩 모델 파인튜닝

- 임베딩 모델 파인튜닝은 사전 학습된 임베딩 모델을 특정 도메인이나 작업에 맞게 최적화하는 과정입니다.

## 1. 임베딩 모델의 학습 원리

- 의미가 비슷한 문장 쌍에는 높은 임베딩 유사도를, 의미가 다른 문장 쌍에는 낮은 유사도를 반환하도록 임베딩 벡터를 업데이트 하는 방식입니다.
- 임베딩 모델을 학습할 때는 의미가 유사한 문장 쌍과 유사하지 않은 문장 쌍을 대조하여 학습하는 방식, 즉 대조 학습을 활용합니다.

### 1.1 대조학습

- 포지티브 샘플
  - 의미적으로 관련이 있는 문장 쌍을 의미합니다.
  - 예: (기준 문서: "서울의 인구는?", 비교 문서: "서울의 인구는 약 970만명 입니다.")
- 네커티브 샘플
  - 기준 문서는 동일하지만, 비교 문서는 의미적으로 관련이 없거나 관련성이 낮은 문장을 준비하여 이들을 쌍으로 구성한 데이터입니다.
  - 예: (기준 문서: "서울의 인구는?", 비교 문서: "파리는 프랑스의 수도입니다.")

- 포지티브 샘플은 RAG를 수행할 때 사용자가 입력할 만한 검색어를 기준문서, 검색 결과로 유사도가 높게 나오기를 바라는 문서를 관련 있는 문서로 삼아 구성합니다.
- 네거티브 샘플은 RAG상황에서 같은 앵커에 대한 검색 결과에 포함되지 않기를 바라는 문서를 짝지어 구성합니다.

- 포지티브 샘플과 네거티브 샘플 구성
  - 기준 문서를 중심으로 유사도가 높은 쌍인 포지티브 샘플(관련 있는 쌍)과 유사도가 낮은 네거티브 샘플(관련 없는 쌍)을 모두 학습 데이터로 준비합니다.
- 대조 학습
  - 모델이 포지티브 샘플 쌍의 임베딩 간 거리는 가깝게, 네거티브 샘플 쌍의 임베딩 간 거리는 멀게 만들도록 학습합니다.
- 손실 함수 최적화
  - 임베딩 간 유사도를 계산하여, 포지티브 쌍의 임베딩 유사도는 높이고 네거티브 쌍의 임베딩 유사도는 낮추는 방향으로 손실 함수를 최적화합니다.

- 손실 함수는 모델이 예측한 결과와 실제 정답 간의 오차를 계산해 학습을 조정하는 기준이 됩니다.
- MultipleNegativesRankingLoss라는 손실 함수를 사용할 예정입니다.

### 1.2 데이터셋 구성

- 대조 학습에서는 하나의 기준 문서에 대해 하나의 포지티브 샘플과 하나 이상의 네거티브 샘플을 명시적으로 준비해야 합니다.
- 기준 문서는 앵커라고 부릅니다.
- 네거티브 샘플은 포지티브 샘플보다 양이 많을수록 좋습니다.

- 트리플렛 구성
  - 전통적인 방식은 각 학습 데이터를 (앵커, 포지티브, 네거티브) 형태의 트리플렛으로 구성하는 것입니다.

In [ ]:
# 전통적인 트리플렛 구성 예
triplets = [
    # (앵커, 포지티브, 네거티브)
    ("강아지를 기르는 방법", "반려견 양육 가이드", "고양이 사료 추천"),
    ("파이썬 코딩 튜토리얼", "파이썬 프로그래밍 기초", "자바스크립트 입문 강의"),
    # 수천, 수만 개의 트래플렛 필요
]

- 다중 네거티브 구성
  - 실제 모델 학습에서는 하나의 앵커에 여러개의 네거티브 샘플을 포함하는 구성이 더 효과적인 경우가 많습니다.

In [ ]:
# 다중 네거티브 샘플 구성 예
training_data = [
    {
        "anchor": "머신러닝이란?",
        "positive": "기계학습은 데이터로부터 패턴을 찾는 AI 기술입니다.",
        "negatives": [
            "오늘 날씨가 좋네요",
            "내일 회의는 2시에 시작합니다.이 식당의 불고기가 맛있습니다.",
            # 여러 개의 네거티브 샘플
        ],
    },
    # 수천개의 이러한 구조
]

- 다중 네거티브 구성은 학습 효과를 높일 수 있지만, 그만큼 데이터 준비의 난이도도 높아집니다.
- 임베딩 모델을 효과적으로 파인튜닝하기 위해서는, 특히 네거티브 샘플 선정이 가장 까다로운 작업중 하나입니다.

- 네거티브 샘플의 문서는 각 앵커와 관련 없는 텍스트여야만 합니다.
- 적절한 난이도의 네거티브 샘플을 선택해야 합니다.
  - 두 개의 쌍이 너무 관련이 없다면 임베딩 모델이 판단하기 너무 쉬워서 학습 효과가 거의 없게 됩니다.
  - 사람이 보아도 관련이 있는 것인지 관련이 없는 것인지 헷갈릴 정도의 문서 쌍이라면 난이도가 너무 높아져 학습에 오히려 방해가 됩니다.
- 다중 네거티브 샘플을 구성할 경우, 네거티브 샘플을 포지티브 샘플 대비 몇 배로 구성하느냐에 따라 데이터셋 크기가 기하급수적으로 증가하고, 만들어야 하는 데이터의 양이 많아지게 됩니다.

- 임베딩 파인튜닝에서 양질의 네거티브 샘플을 구성하는 것은 종종 전체 학습과정에서 가장 어려운 부분 중 하나입니다.

### 1.3 배치 내 네거티브 샘플링

- 배치 내에서 네거티브 샘플을 선정하는 학습 방법을 사용합니다.
- 이 방법은 명시적인 네거티브 샘플을 별도로 준비할 필요가 없다는 큰 장점이 있습니다.
- 학습 데이터에서 다른 앵커에서 사용하고 있는 샘플을 참고하여 자동으로 네거티브로 활용합니다.
- 이 원리를 이해하려면 배치라는 개념을 알아야 합니다.
- AI모델은 데이터를 적당한 개수의 묶음으로 나누어 학습합니다.
- 예를 들어 데이터가 5000개 이고 배치 크기를 40으로 설정했다면, 데이터를 40개씩 묶어 125회에 걸쳐 학습하게 됩니다.
- 배치란 모델이 한 번에 학습하는 데이터의 단위를 뜻하며, 병렬적으로 데이터를 몇개씩 학습할 것이냐를 의미합니다.

- 배치 내 네거티브 생성 방법은 포지티브 샘플만으로 데이터를 구성하더라도 배치내에서 네거티브 샘플들을 자동으로 만드는 학습 방법입니다.
- 사용자는 학습을 위해 포지티브 샘플만 제공하면 되며, 네거티브 샘플은 학습 시 배치내에서 자동으로 생성됩니다.

- 예를 들어 배치 크기가 4인 경우, 한번의 학습에 네 개의 서로 다른 앵커 문서와 그에 대응하는 포지티브 샘플이 사용되며, 이들 간 교차로 네거티브 샘플 역할도 동시에 수행됩니다.

```
배치 = [
    (앵커문서1, 문서1),
    (앵커문서2, 문서2),
    (앵커문서3, 문서3),
    (앵커문서4, 문서4)
]
```

- 앵커 문서1의 포지티브는 문서1, 나머지는 네거티브로 간주됩니다.
- 앵커 문서2의 포지티브는 문서2, 나머지는 네거티브로 간주됩니다.

- 하나의 배치 안에서 다른 쌍의 문서를 네거티브로 자동 활용하면서 대조 학습을 수행합니다.

```
[
    ("AI란 무엇인가?", "AI는 인간의 지능을 모방한 기술입니다."),
    ("딥러닝이란?", "신경망을 여러 층 쌓아 데이터로부터 학습하는 기계학습 방법입니다."),
    ("Python은 어디에 쓰이나요?", "Python은 데이터 분석, 웹 개발, AI 등에 널리 사용됩니다."),
    ("자연어 처리란?" , "컴퓨터가 인간의 언어를 이해하고 처리하는 AI의 한 분야입니다.")
]
```

### MultipleNegativesRankingLoss

- 이 손실 함수는 포지티브 샘플과의 유사도는 높이고, 네거티브 샘플과는 유사도는 낮추도록 설계되어 있습니다.

In [1]:
from sentence_transformers import SentenceTransformer, losses, InputExample
from torch.utils.data import DataLoader
import torch

# 모델 로드
model = SentenceTransformer("BAAI/bge-m3")

# 훈련 데이터 준비
train_examples = [
    InputExample(texts=["AI란 무엇인가?", "AI는 인간의 지능을 모방한 기술입니다."]),
    InputExample(
        texts=[
            "딥러닝이란?",
            "신경망을 여러 층 쌓아 데이터로부터 학습하는 기계학습 방법입니다.",
        ]
    ),
    InputExample(
        texts=[
            "Python은 어디에 쓰이나요?",
            "Python은 데이터 분석, 웹 개발, AI등에 널리 사용됩니다.",
        ]
    ),
    InputExample(
        texts=[
            "자연어 처리란?",
            "컴퓨터가 인간의 언어를 이해하고 처리하는 AI의 한 분야입니다.",
        ]
    ),
]

# 배치 크기가 클수록 성능이 향상될 수 있지만 GPU에 따라서 최대 비치 크기가 제한됨
batch_size = 32
train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=batch_size)

# MultipleNegativesRankingLoss 설정
# 온도(temperature) 파라미터를 조정하여 손실 함수의 강도 조절 가능
loss = losses.MultipleNegativesRankingLoss(
    model, scale=20.0
)  # scale은 temperature의 역수

# 학습 설정
train_loss = losses.MultipleNegativesRankingLoss(model)
warmup_steps = int(len(train_dataloader) * 0.1)  # 전체 훈련 데이터의 10%

# 모델 학습
model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=3,
    warmup_steps=warmup_steps,
    optimizer_params={"lr": 2e-5},
    output_path="./korean-sentence-embedding-model",
)

c:\workspace\python\rag_master\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\workspace\python\rag_master\.venv\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

- 먼저 sentence_transformers 라이브러리를 통해 BAAI/bge-m3 모델을 기본 모델로 로드합니다.
- 이어 훈련데이터를 InputExample객체의 리스트로 준비합니다.
- 모델은 이러한 문장의 쌍들을 통해 유사한 문장들이 임베딩 공간에서 가깝게 위치하도록 학습합니다.
- DataLoader를 활용하여 배치크기 32로 데이터를 효율적으로 처리하도록 설정합니다.
  - 데이터가 4개밖에 없지만, 실제 상황에서는 데이터가 32개보다 많다고 가정합니다.
- 손실함수로 MultipleNegativesRankingLoss를 채택했습니다. 의미적으로 유사한 문장들은 가깝게, 그렇지 않은 문장들은 멀리 위치시키도록 모델을 유도합니다.
  - scale=20.0 파라미터는 온도의 역수로 손실함숨의 강도를 적절히 조절하는 역할을 합니다.
- 학습과정에서는 워밍업단계를 전체 훈련데이터의 10%로 설정합니다.
- 업데이트 하는 정도를 조절하는 학습률은 2e-5 로 지정합니다.
- model.fit() 함수를 호출하여 모델을 학습합니다.
- 학습횟수를 의미하는 에포크의 경우 3
- 완성된 모델은 korean-sentence-embedding-model 디렉터리에 저장합니다.

## 2 학습 시 성능을 높이는 방법

### 3.1 배치 크기 키우기

- 임베딩 모델을 효과적으로 학습시키려면 배치 크기를 크게 설정하는 것이 중요한 전략 중 하나입니다.
- 대조 학습은 동일 앵커 기준으로 네거티브 샘플이 포지티브 샘플보다 많을수록 학습 성능이 올라간다는 특징이 있습니다.
- 배치 크기가 4인 경우: 각 질문에 대해 3개의 네거티브 샘플
- 배치 크기가 32인 경우: 각 질문에 대해 31개의 네거티브 샘플
- 배치 크기는 GPU 메모리 용량에 따라 제한되므로 무한정 키울수는 없습니다.
- 구글 코랩에서 제공되는 무료 GPU를 사용할 경우 배치 크기는 3~4수준에 그치는 경우가 많습니다.

### 2.2 하드 네거티브 선정

- 더 어려운 네거티브 샘플, 하드 네거티브를 추가하면 성능을 더욱 향상시킬 수 있습니다.
- 하드네거티브는 명시적으로 사용자가 직접 선택하여 학습 데이터에 포함시키는 네거티브 샘플을 의미합니다.

In [ ]:
# 하드 네거티브 예제
train_examples = [
    # (앵커, 포지티브, 하드 네거티브 형태로 제공)
    InputExample(
        texts=[
            "AI란 무엇인가?",
            "AI는 인간의 지능을 모방한 기술입니다.",
            "AI는 로봇과 같은 물리적 형태를 가진 기계입니다.",
        ]
    ),
    InputExample(
        texts=[
            "딥러닝이란?",
            "신경망을 여러 층 쌓아 데이터로부터 학습하는 기계학습 방법입니다.",
            "컴퓨터가 스스로 생각하는 방법입니다.",
        ]
    ),
]

- 각 InputExample의 첫 번째 항목은 앵커(질문)입니다.
- 두 번째 항목은 포지티브 샘플(관련있는응답)입니다.
- 세 번째 이후 항목들은 하드 네거티브(관련 없지만 구분하기 어려운 응답)입니다.

- 손실함수는 각 쌍에 대해 다른 모든 앵커의 포지티브 샘플들과 모든 하드 네거티브 샘플들을 네거티브로 사용합니다.
- 포지티브와 유사도가 높아지도록 학습되고, 다른 앵커의 포지티브, 하드 네거티브와는 유사도가 낮아지도록 학습됩니다.

- 일반 네거티브(배치 내 무작위 네거티브)
  - 자동으로 배치 내에서 생성됨
  - 대부분 주제가 완전히 다른 무관한 문장들
  - 모델이 구분하기 상대적으로 쉬움
- 하드 네거티브(명시적 네거티브)
  - 사용자가 직접, 의도적으로 선택함
  - 포지티브와 주제는 유사하나 정확한 답변은 아님
  - 미묘한 의미 차이를 포함하여 모델에게 더 큰 도전이 됨
- 예시
  - 질문: 당뇨병의 증상은 무엇인가요?
  - 포지티브: 당뇨병의 주요 증상으로는 갈증 증가, 빈뇨, 체중 감소 등이 있습니다.
  - 하드 네거티브(명시적): 저혈당의 증상으로는 현기증, 발한, 불안감 등이 있습니다. (의료 관련 주제이지만 당뇨병이 아닌 저혈당에 관한 내용)
  - 일반 네거티브(배치 내 자동 선택): 파이썬은 객체지향 프로그래밍 언어입니다.(완전히 다른 주제)

- 하드 네거티브 샘플을 사용하면 모델이 더 미묘한 의미 차이를 학습하게 되어 정확도가 크게 향상될 수 있습니다.
- 가능하다면 일반 네거티브와 하드 네거티브를 병행해 사용하는 것이 이상적입니다.

### 2.3 그 외 학습 성능 향상을 위한 팁

- 학습 데이터와 실전과의 괴리 최소화
  - 학습에 사용할 데이터의 앵커는 실제 RAG에서 사용자가 입력할만한 질문으로 구성해야 합니다. 학습 데이터와 실제 RAG에서 입력될 질문의 차이가 클수록 학습 후의 효용은 떨어지기 마련입니다.
- 데이터 증강
  - 난이도가 높은 하드 네거티브 샘플은 충분히 확보하면 모델이 더 섬세한 의미 차이를 학습할 수 있어 성능 향상에 도움이 됩니다.
- 학습률 조정
  - 학습률을 바꿔가면서 여러 번 학습하여 모델의 성능을 평가하고, 최적의 학습률을 찾아보는 것이 좋습니다.
- 온도 파라미터 조정
  - 손실 함수의 scale파라미터를 조절하면 학습 강도를 세밀하게 조정할 수 있습니다.

## 3. 실전 파인튜닝

### 3.1 데이터 로드하기

In [1]:
import os
import requests
import json
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
from openai import OpenAI
from torch.utils.data import DataLoader
from sentence_transformers import SentenceTransformer, losses, InputExample
from sentence_transformers.evaluation import InformationRetrievalEvaluator
import torch
from sklearn.metrics.pairwise import cosine_similarity
import PyPDF2

- os: 환경 변수 설정에 사용되며, 임베딩 모델 파인튜닝 과정에서 오픈AI API키를 설정합니다.
- requests: PDF파일과 같은 학습 데이터를 인터넷에서 다운로드할 때 사용합니다.
- json: API 응답을 처리하거나 구성 설정을 저장/로드할 때 활용합니다.
- pandas: 임베딩 모델 성능 평가 결과를 데이터프레임으로 구성하고 분석하는 데 사용합니다.
- numpy: 벡터 연산을 수행하며 특히 임베딩 벡터 간 코사인 유사도 계산에 사용합니다.
- tqdm: 대용량 데이터셋을 처리할 때 진행 상황을 시각적으로 표시하여 학습 과정을 모니터링 합니다.
- OpenAI: GPT 모델을 사용해 문서로부터 질문을 생성하는 등의 작업에 활용합니다.
- DataLoader: 임베딩 모델 학습 시 배치 단위로 데이터를 효율적으로 로드합니다. 이때, 배치 크기는 성능에 큰 영향을 미칩니다.
- SentenceTransformer: 문장 임베딩 모델의 핵심 라이브러리로, 다양한 사전 학습 모델을 로드하고 파인튜닝합니다.
- losses: MultipleNegativesRankingLoss와 같은 손실함수를 제공하여 임베딩 모델이 관련 문서 쌍은 가깝게, 관련 없는 쌍은 멀게 학습하도록 합니다.
- InputExample: 파인튜닝용 학습데이터 포맷으로, 질문과 관련 문서 쌍을 모델이 이해할 수 있는 형태로 구성합니다.
- InformationRetrievalEvaluator: 파인튜닝된 모델의 검색 성능을 정확도, MRR, NDCG등 다양한 지표로 평가합니다.
- torch: 임베딩 모델의 기본 프레임워크로, 텐서 연산과 GPU 가속을 지원합니다.
- cosine_similarity: 임베딩 벡터 간 유사도를 계산하여 질문에 가장 관련성 높은 문서를 찾는 데 사용합니다.
- PyPDF2: PDF 파일을 읽는데 사용합니다.

In [2]:
from dotenv import load_dotenv

# .env 파일에서 환경 변수 로드
load_dotenv()
# 환경 변수에서 API 키 가져오기
api_key = os.getenv("OPENAI_API_KEY")

### 3.2 하드 네거티브 선정

- 깃허브 저장소에서 일본 ICT 동향 문서와 미국 ICT 동향 문서 두 가지를 다운로드합니다.
- 미국 ICT 동향 문서를 기준으로 임베딩 모델을 학습시키고, 동일한 도메인의 문서인 일본 ICT 동향 문서에 대해 검색 성능을 평가해보겠습니다.
- 실제 현업에서 임베딩 모델을 파인튜닝할 때도 실제 RAG에서 사용할 동일한 도메인의 데이터로 파인튜닝하면 더 좋은 효과를 얻을 수 있습니다.

In [4]:
# PDF 파일 다운로드
urls = [
    "https://raw.githubusercontent.com/langchain-kr/langchain-tutorial/main/Ch09.%20Embedding%20Fine-tuning/ict_japan_2024.pdf",
    "https://raw.githubusercontent.com/langchain-kr/langchain-tutorial/main/Ch09.%20Embedding%20Fine-tuning/ict_usa_2024.pdf",
]

for url in urls:
    filename = url.split("/")[-1]
    response = requests.get(url)
    with open(filename, "wb") as f:
        f.write(response.content)
    print(f"{filename} 다운로드 완료")

ict_japan_2024.pdf 다운로드 완료
ict_usa_2024.pdf 다운로드 완료

In [3]:
def extract_text_from_pdf(pdf_path):
    """PDF 파일에서 텍스트를 추출하는 함수"""
    text_chunks = []
    with open(pdf_path, "rb") as file:
        pdf_reader = PyPDF2.PdfReader(file)
        for page_num in range(len(pdf_reader.pages)):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            # 페이지 단위로 청크 생성
            if text.strip():
                text = text.strip()
                # 문서 길이가 10자 초과인 경우만 추가
                if len(text) > 10:
                    text_chunks.append(text)
    return text_chunks


# 미국 ICT 동향(학습 데이터)
train_corpus = extract_text_from_pdf("ict_usa_2024.pdf")
print(f"학습 데이터 문서 개수: {len(train_corpus)}")

# 일본 ICT 동향(검증 데이터)
val_corpus = extract_text_from_pdf("ict_japan_2024.pdf")
print(f"검증 데이터 문서 개수: {len(val_corpus)}")

학습 데이터 문서 개수: 26
검증 데이터 문서 개수: 27

- 의미 있는 내용을 보장하기 위해 길이가 10자를 초과하는 텍스트만 청크에 추가합니다.

In [4]:
print("10번 문서:", train_corpus[10])

10번 문서: 13 Ⅰ. ICT 국가 산업 현황
 4.ICT 주요 법령 및 규제
  ② 반도체 과학법 (CHIPS and Science Act)
 반도체 ·전자 기업, $1,660 억 규모 투자 유치
• 조 바이든 (Joe Biden) 미국 대통령은 2022년 7월 ‘반도체 과학법 (CHIPS and Science Act)’을 승인함
• 반도체 과학법은 미국의 경쟁력을 강화하고 , 미국의 공급망을 탄력적으로 구축해 국가 안보를
공고히 하며 국가의 주요 기술에 대한 접근을 지원하는 것을 목표로 함. 법률 제정으로 미국 내
반도체 생산 제조사 관련 자본 투자는 25%의 세액 공제 혜택이 제공됨
• 미국 백악관은 2023년 8월, 반도체 과학법이 서명된 지 1년 만에 반도체와 전자 관련 기업들이
1,660 억 달러(221조6,100 억 원)의 투자를 유치했다고 발표함 . 바이든 행정부의 집권 이후 기업들은
미국 내 반도체와 전자 분야 투자에 총 2,310 억 달러(약 308조 3,850 억 원) 이상의 투자를 약속함
[표 8] 반도체 과학법 주요 이정표 및 진척 현황
주요 이정표 진척 현황 (23년 8월 기준)
미국 반도체 제조
지원‣ 상무부는 CHIPS 통과 6개월 만에 해당 법에서 제공하는 390억 달러 반도체 제조
인센티브에 대한 첫 번째 자금 조달 기회 시작
‣ 상무부는 42개 주에서 CHIPS 자금 지원에 관심 있는 460개 기업으로부터 소개서 접수
‣ 상무부는 CHIPS 인센티브 프로그램 관련 140명 이상의 인력으로 구성된 ‘칩스 포
아메리카 (CHIPS for America)’ 팀 구성
‣ 재무부는 투자에 대한 25% 세액 공제 관련 지침 제공 위해 규칙 제안 발표
국가 안보를
보호하고 동맹국 및
파트너와 협력‣ 국무부는 국제 기술 보안 및 혁신 기금 시행 계획 발표
‣ 국방부와 상무부는 CHIPS 투자를 통한 안보 관련 반도체 제조를 위해 협력 확대 협의
‣ CHIPS 를 시행하면서 상무부는 여러 파트너 및 동맹국과 긴밀한 접촉 유지
미국 근로자를 위한
일자리 및 인력
파이프라인 창출‣ 반도체 및 기타 산업에서 양질의 일자리를 창출할 파이프라인 구축을 위해 5개의 인력
허브 초기 세트 발표
‣ 최소 50개 이상의 커뮤니티 대학에서 신규 및 확장된 반도체 인력 프로그램 발표
‣ 국립과학재단 (NSF) 은 제조 인력 및 연구자 지원, 커리큘럼 개발에 초점을 맞춘 새로운
계획을 통해 미국 반도체 인력 투자
‣ 반도체 기업의 정규직 채용에 지원한 학생 수는 2022~2023 년에 79% 증가
혁신 투자‣ 상무부는 기타 부처들과 국립 반도체 기술 센터 설립 추진
‣ 상무부는 110억 달러 규모의 R&D 자금을 계측 프로그램 , 국립 고급 포장 제조 프로그램 ,
최대 3개의 신규 ‘Manufacturing USA’ 연구소 등 기타 부문에도 투자
‣ 국방부는 마이크로전자공학 공용 R&D 프로그램에 대한 솔루션 요청서 발표
지역 경제 개발 및
혁신 지원‣ 상무부는 5억 달러 규모의 기술 허브 프로그램 1단계를 위한 자금 조달 기회 발표
‣ 낙후 지역 경제발전 및 일자리 창출을 위한 Recompete 프로그램 1단계에 2억 달러 자금
조달 기회 발표
‣ 국립과학재단은 기술, 혁신, 파트너십을 위한 새로운 부서 설립
무선 혁신 및
보안 지원‣ 상무부는 개방적이고 상호 운용 가능한 무선 네트워크 개발 지원을 위해 15억 달러 규모의
공공 무선 공급망 혁신 기금의 첫 번째 보조금 발표
출처 : 미국 백악관

##

## 합성 데이터 생성

- 배치 인 네거티브 샘플 선정 방법을 사용하므로 네거티브 샘플을 따로 준비할 필요는 없습니다.
- gpt api를 이용하여 자동으로 포지티브 샘플을 만들어 보겠습니다.

In [5]:
# OpenAI 클라이언트 초기화
client = OpenAI()


# 각 문서에 대한 질문 생성(OpenAI API 사용)
def generate_queries(corpus, num_questions_per_chunk=2):
    all_queries = []
    all_positive_docs = []

    # 기본 프롬프트 템플릿 설정
    prompt_template = """
    다음은 참고할 내용입니다.

    ----------------------
    {context_str}
    ----------------------
    위 내용을 바탕으로 낼 수 있는 질문을 {num_questions_per_chunk}개 만들어 주세요.
    질문만 작성하고 실제 정답이나 보기 등은 작성하지 않습니다.

    해당 질문은 본문을 볼 수 없다고 가정합니다.
    따라서 '위 본문을 바탕으로~' 라는 식의 질문은 할 수 없습니다.

    질문은 아래와 같은 형식으로 번호를 나열하여 생성하십시오.

    1. (질문)
    2. (질문)
    """

    # corpus의 각 문서에 대해 반복 실행
    for text in tqdm(corpus):
        # 현재 문서에 대한 프롬프트 생성
        messages = [
            {
                "role": "system",
                "content": "You are a helpful assistant that generates questions based on provided content.",
            },
            {
                "role": "user",
                "content": prompt_template.format(
                    context_str=text, num_questions_per_chunk=num_questions_per_chunk
                ),
            },
        ]

        # GPT 모델을 사용해 질문 생성
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=messages,
            temperature=0.7,
        )

        # 응답을 줄바꿈을 기준으로 분리하여 개별 질문으로 만듦
        result = response.choices[0].message.content.strip().split("\n")

        # 질문 형식 정리
        questions = []
        for line in result:
            if line.strip():
                parts = line.strip().split(". ", 1)
                if len(parts) > 1:
                    questions.append(parts[1])
                else:
                    questions.append(parts[0])

        # 빈 질문 제거
        questions = [q for q in questions if len(q) > 0]

        # 각 질문에 대해 문서 매칭 및 저장
        for question in questions:
            all_queries.append(question)
            all_positive_docs.append(text)

    return all_queries, all_positive_docs

- generate_queries 함수는 PDF에서 추출한 텍스트 데이터 train_corpus와 val_corpus를 입력 받아 처리합니다.
- 각 텍스트 문서마다 GPT모델에게 질문 생성을 요청합니다.
- 각 문서당 2개의 질문을 생성하도록 지정합니다.

### 예

- "2024년 일본 반도체 산업은 전년 대비 15% 성장했으며, 정부는 300억 엔의 추가 투자를 발표했다."
- "2024년 일본 반도체 산업의 성장률은 얼마인가?"
- "일본 정부가 반도체 산업에 발표한 추가 투자 금액은?"

- all_queries: 생성된 모든 질문이 들어 있습니다.
- all_positive_docs: 각 질문의 출처가 된 문서들이 순서대로 들어 있습니다.

- 합성 데이터를 생성하는 작업은 실제 실무에 적용할 때는 현재 구현하는 RAG 시스템의 실제 상황에서 사용자가 입력할 만한 질문들이 생성되도록 프롬프트를 조정하는 것이 바람직합니다.

In [6]:
# 학습 데이터 질문 생성
train_queries, train_positive_docs = generate_queries(train_corpus)
print(f"생성된 학습용 질문 개수: {len(train_queries)}")

# 검증 데이터 질문 생성
val_queries, val_positive_docs = generate_queries(val_corpus)
print(f"생성된 검증용 질문 개수: {len(val_queries)}")

  0%|          | 0/26 [00:00<?, ?it/s]

생성된 학습용 질문 개수: 52

  0%|          | 0/27 [00:00<?, ?it/s]

생성된 검증용 질문 개수: 54

- train_queries에는 '미국 ICT 동향 문서'로부터 만들어낸 26개의 문서에 해당하는 train_corpus를 입력하여 만든 질문들이 저장되어 있습니다.
- 2개씩 생성하도록 지정했기 때문에 총 52개의 질문이 만들어졌습니다.
- 같은 원리로 val_queries는 '일본 ICT 동향 문서' 27개이므로 총 54개의 포지티브 샘플입니다.
- 이제 이 데이터를 학습에 사용할 수 있도록 InputExample 객체의 리스트 형태로 변환합니다.

In [7]:
# 학습 데이터 준비
train_examples = []
for query, doc in zip(train_queries, train_positive_docs):
    example = InputExample(texts=[query, doc])
    train_examples.append(example)

In [8]:
# 첫번째 데이터 출력
train_examples[0].texts

['ICT 관련 주요 정책과 법령에는 어떤 내용이 포함되어 있는가?',
 'Ⅰ ICT국가산업현황  4\n(*) SUMMARY\n1. 국가 개황\n2. ICT 정부기구\n3. ICT 주요정책\n4. ICT 주요법령및규제\n5. ICT 주요기업\n6. 한국 협력 및 국내기업 진출사례\nⅡ ICT이슈Top 10  16\n(*) SUMMARY\n① 미국 빅테크 기업, 인공지능 챗봇 개발에 주력\n② 미국, 일본과 양자컴퓨팅 개발 협력\n③ 미국, 우주 클라우드 컴퓨팅 시장 주도\n④ 미국, 드론 배송 도입 활발\n⑤ 미국, 긍정적인 의료 AI 인식 바탕으로 연구 활발\n⑥ 미국, 반도체 산업 활성화에 박차\n⑦ 미국, 기술 교류를 위한 국가 간 협력 활발\n⑧ 미국, 사이버 보안 대응 강화\n⑨ 미국, 6G 주도권 확보 위한 연구 추진\n⑩ 미 국방부 , 디지털 트윈 기술 도입 확대\n※ 참고문헌']

- 출력 결과를 보면 두 개의 원소를 지닌 리스트가 출력되는데, 각각 생성한 질문과 질문을 생성하기 위해 참고한 문서입니다.
- 이 둘은 서로 연관이 있는 질문과 문서이므로 포지티브 샘플 관계입니다.
- 두 번째 데이터를 출력해 봅시다.

In [9]:
# 첫번째 데이터 출력
train_examples[1].texts

['미국의 빅테크 기업들이 최근 집중하고 있는 기술 개발 분야는 무엇인가?',
 'Ⅰ ICT국가산업현황  4\n(*) SUMMARY\n1. 국가 개황\n2. ICT 정부기구\n3. ICT 주요정책\n4. ICT 주요법령및규제\n5. ICT 주요기업\n6. 한국 협력 및 국내기업 진출사례\nⅡ ICT이슈Top 10  16\n(*) SUMMARY\n① 미국 빅테크 기업, 인공지능 챗봇 개발에 주력\n② 미국, 일본과 양자컴퓨팅 개발 협력\n③ 미국, 우주 클라우드 컴퓨팅 시장 주도\n④ 미국, 드론 배송 도입 활발\n⑤ 미국, 긍정적인 의료 AI 인식 바탕으로 연구 활발\n⑥ 미국, 반도체 산업 활성화에 박차\n⑦ 미국, 기술 교류를 위한 국가 간 협력 활발\n⑧ 미국, 사이버 보안 대응 강화\n⑨ 미국, 6G 주도권 확보 위한 연구 추진\n⑩ 미 국방부 , 디지털 트윈 기술 도입 확대\n※ 참고문헌']

- 동일한 문서에 대해 질문이 2개 이므로 질문은 동일합니다.

## 3.4 모델 로드하기

- 배치 크기, 학습할 모델, 사용할 손실 함수를 설정합니다.
- 배치 크기를 4로 설정하겠습니다.
- DataLoader() 에 train_examples를 전달하고 batch_size값을 4로 설정합니다.
- 총 54개의 학습데이터는 4개씩 묶여 배치 단위로 처리됩니다.
- 일반적으로 배치 크기가 클수록 더 많은 네거티브 샘플이 생성되므로 성능이 더 좋아질 수 있습니다.

In [10]:
BATCH_SIZE = 4  # 배치 크기 조정
loader = DataLoader(train_examples, batch_size=BATCH_SIZE, shuffle=True)

- 이제 학습에 사용할 모델을 선택합니다.
- SentenceTransformer 모듈을 사용하여 허깅페이스 저장소로부터 모델을 다운로드 합니다.

In [11]:
# 모델 설정
model_id = "BAAI/bge-m3"
model = SentenceTransformer(model_id)

- 손실 함수로는 MultipleNegativesRankingLoss를 사용합니다.
- 포지티브 샘플과의 유사도는 높일수록 좋습니다. 즉, 검색어(앵커)와 관련 있는 문서가 가까이 있도록 학습합니다
- 네거티브 샘플과의 유사도는 낮을수록 좋습니다. 즉, 관련 없는 문서는 멀어지도록 학습합니다.

In [12]:
# 손실 함수 설정
loss = losses.MultipleNegativesRankingLoss(model)

## 3.5 평가 데이터 전처리

- 검색 성능을 평가하는데 InformationRetrievalEvaluator를 사용합니다.
- 이 도구를 사용하려면 평가 데이터를 특정 형식으로 전처리해야 합니다.
- InformationRetrievalEvaluator는 정보 검색 모델을 평가하는 도구로 3가지 필수 데이터 구조를 입력 받습니다.

### 1. queries

- 질문 ID를 키로, 질문 텍스트를 값으로 갖는 파이썬 딕셔너리입니다.

```json
{
  "q1": "인공지능의 정의는 무엇인가?",
  "q2": "머신러닝과 딥러닝의 차이점은?",
  "q3": "자연어 처리란 무엇인가?"
}
```

### 2. corpus

- 문서 ID를 키로, 문서 텍스트를 값으로 갖는 파이썬 딕셔너리입니다.

```json
{
  "d1": "인공지능(AI)은 인간의 학습, 추론, 결정 능력 등을 컴퓨터 시스템으로 구현한 기술이다. 인공지능은 머신러닝, 딥러닝 등 다양한 하위 분야를 포함한다.",
  "d2": "머신러닝은 컴퓨터가 데이터로부터 패턴을 학습하여 예측이나 의사결정을 수행하는 기술이다. 반면 딥러닝은 인공 신경망을 활용하여 더 복잡한 패턴을 학습하는 머신러닝의 한 분야이다.",
  "d3": "자연어 처리(NLP)는 컴퓨터가 인간의 언어를 이해, 해석, 생성할 수 있도록 하는 인공지능의 한 분야이다. 기계번역, 감성분석, 텍스트 요약 등의 응용이 있다."
}
```

### 3. relevant_docs

- 질문ID를 키로, 해당 질문에 관련된 문서 ID들의 집합(set)을 값으로 갖는 파이썬 딕셔너리입니다.

```python
{
    "q1": set(["d1"]),  #인공지능 질문은 d1 문서와 관련
    "q2": set(["d2"]),  #머신러닝/딥러닝 질문은 d2 문서와 관련
    "q3": set(["d3"])   #자연어 처리 질문은 d3 문서와 관련
}
```

- 실제 코드를 가정하여 구체적으로 예를 들어 살펴보겠습니다.

```python
# 기존에 전처리한 형태
val_queries = [
    "인공지능의 정의는 무엇인가?",
    "머신러닝과 딥러닝의 차이점은?",
    "자연어 처리란 무엇인가?",
]
val_positive_docs = [
    "인공지능(AI)은 인간의 학습, 추론, 결정 능력 등을 컴퓨터 시스템으로 구현한 기술이다. 인공지능은 머신러닝, 딥러닝 등 다양한 하위 분야를 포함한다.",
    "머신러닝은 컴퓨터가 데이터로부터 패턴을 학습하여 예측이나 의사결정을 수행하는 기술이다. 반면 딥러닝은 인공 신경망을 활용하여 더 복잡한 패턴을 학습하는 머신러닝의 한 분야이다.",
    "자연어 처리(NLP)는 컴퓨터가 인간의 언어를 이해, 해석, 생성할 수 있도록 하는 인공지능의 한 분야이다. 기계번역, 감성분석, 텍스트 요약 등의 응용이 있다.",
]

# InformationRetrievalEvaluator를 위한 변환
val_dataset = {
    "queries": {
        "q1": "인공지능의 정의는 무엇인가?",
        "q2": "머신러닝과 딥러닝의 차이점은?",
        "q3": "자연어 처리란 무엇인가?",
    },
    "corpus": {
        "d1": "인공지능(AI)은 인간의 학습, 추론, 결정 능력 등을 컴퓨터 시스템으로 구현한 기술이다. 인공지능은 머신러닝, 딥러닝 등 다양한 하위 분야를 포함한다.",
        "d2": "머신러닝은 컴퓨터가 데이터로부터 패턴을 학습하여 예측이나 의사결정을 수행하는 기술이다. 반면 딥러닝은 인공 신경망을 활용하여 더 복잡한 패턴을 학습하는 머신러닝의 한 분야이다.",
        "d3": "자연어 처리(NLP)는 컴퓨터가 인간의 언어를 이해, 해석, 생성할 수 있도록 하는 인공지능의 한 분야이다. 기계번역, 감성분석, 텍스트 요약 등의 응용이 있다.",
    },
    "relevant_docs": {
        "q1": set(["d1"]),  # 인공지능 질문은 d1 문서와 관련
        "q2": set(["d2"]),  # 머신러닝/딥러닝 질문은 d2 문서와 관련
        "q3": set(["d3"]),  # 자연어 처리 질문은 d3 문서와 관련
    },
}
```

In [13]:
# 평가 데이터셋 구성
val_dataset = {"queries": {}, "corpus": {}, "relevant_docs": {}}

# 문서 ID를 먼저 생성
doc_ids = {}
for i, doc in enumerate(val_corpus):
    doc_id = f"q{i}"
    val_dataset["corpus"][doc_id] = doc
    doc_ids[doc] = doc_id

# 질문에 ID를 부여하고 관련 문서 설정
for i, (query, doc) in enumerate(zip(val_queries, val_positive_docs)):
    query_id = f"q{i}"
    val_dataset["queries"][query_id] = query

    # 해당 질문이 어떤 문서에서 왔는지 찾기
    doc_id = doc_ids[doc]

    # 관련 문서 설정
    if query_id not in val_dataset["relevant_docs"]:
        val_dataset["relevant_docs"][query_id] = set()
    val_dataset["relevant_docs"][query_id].add(doc_id)

# 검증 데이터 셋 설정: 평가를 위한 쿼리, 문서, 정답 문서 목록
dataset = val_dataset

- 이제 dataset에는 InformationRetrievalEvaluator를 사용하는데 필요한 데이터인 queries, corpus, relevant_doc가 저장되어 있습니다.

In [14]:
dataset["corpus"]

{'q0': 'Ⅰ ICT국가산업현황  4\n(*) SUMMARY\n1. 국가 개황\n2. ICT 정부기구\n3. ICT 주요정책\n4. ICT 주요법령및규제\n5. ICT 주요기업\n6. 한국 협력 및 국내기업 진출사례\nⅡ ICT이슈Top 10  16\n(*) SUMMARY\n① 일본, 아시아에서 두 번째로 큰 데이터센터 허브\n② 일본, 자체 개발 소프트웨어로 사이버보안 강화\n③ 일본, Web3 산업 성장 촉진 도모\n④ 일본, 정부 행정 업무에 생성형 AI 도입\n⑤ 일본, 첫 자체 제작 양자컴퓨터 공개\n⑥ 일본, 6G 기술 강화 위해 협력 및 규제 완화\n⑦ 일본, 레벨 4 자율주행 허용\n⑧ 일본, 생체인식 결제 도입 증가\n⑨ 일본, 행정 서비스 디지털화 노력\n⑩ 일본, 인재 부족으로 디지털 인력 강화에 힘써\n※ 참고문헌',
 'q1': 'Ⅰ ICT 국가 산업 현황                   4\n   (*) SUMMARY\n   1. 국가 개황\n   2. ICT 정부기구\n   3. ICT 주요 정책\n   4. ICT 주요 법령 및 규제\n   5. ICT 주요기업\n   6. 한국 협력 및 국내기업 진출사례',
 'q2': '5 Ⅰ. ICT 국가 산업 현황\n 1.국가 개황\n 일본, 글로벌 혁신지수 세계 40위\n• 일본의 인터넷 사용자 비중은 82.9% 이며 고정 광대역 가입자 비중은 36.0% 임\n• 일본 글로벌 혁신지수는 세계 13위임. ‘인프라 ’ 및 ‘지식 및 기술 생산’ 지표가 상대적으로 \n우위에 있으며 , ‘창조적 생산’이 상대적 열위를 보임\n 기시다 총리, 결제 활성화 정책에 초점\n• 2023년 일본 물가상승률은 3.1%로 41년에 최대폭을 기록함 . 일본은행은 2023년 12월 \n금융정책결정회의에서 단기금리 목표를 △0.1%로 동결하면서 마이너스 금리 종료를 보류함\n• 일본 기시다 후미오 (岸⽥⽂雄 ) 총리는 향후 경제 활성화를 위한 정책에 초점을 맞출 것임을 밝힘. \n그중에서도 감세 논의에 속도를 내고 있음\n[표 1] 일본 ICT 국가 개황\n구분 기준년도 한국 일본\n일반개황인구 2023 5,150 만 5,000 명 1억 2,404 만 명\n면적(1,000ha) 2023 10,043 37,797\n언어 2023 한국어 일본어\n종교 2023 기독교 , 불교 등 불교, 기독교 등\n정부형태 / 의회제도 2023 대통령제 / 단원제 내각책임제 / 양원제\n경제현황GDP 2023 1.70조 달러 4.21조 달러\n경제 성장률 2023 1.31% 1.56%\nS&P 신용등급 2023 AA A\nICT현황이동전화 가입자 수 2022 149명(100명당) 170명(100명당)\n이동통신 가입자 수 2022 120명(100명당) 234명(100명당)\n유선 브로드밴드 가입자 수 2022 45명(100명당) 37명(100명당)\n인터넷 사용자 비중 2022 97% 85%\n글로벌\n혁신지수총점 (순위) 2023 58.6 (10) 54.6 (13)\n인적자원 및 연구 2023 66.9 (1) 53.8 (18)\n인프라 2023 60.6 (11) 60.3 (13)\n지식 및 기술 생산 2023 53.3 (11) 51.1 (13)\n창조적 생산 2023 58.2 (5) 44.1 (25)\n출처 : World Bank, IMF, 국제전기통신연합 (ITU), 세계지적재산권기구 (WIPO)',
 'q3': '6 Ⅰ. ICT 국가 산업 현황\n 2.ICT 정부기구\n  ① 총무성 (MIC)\n 일본 총무성 (MIC)\n• 일본 총무성 (Ministry of Internal Affairs and Communications) 은 행정, 지방자치 , \n정보통신 , 우정 및 소방분야를 담당하는 일본의 중앙행정기관임 . ICT 관련 역할로 ① 정보의 \n원활한 유통 확보 및 증진, ② 전파의 공평·효율적인 이용의 확보 및 증진, ③ 정보통신 정책의 \n기획과 입안, 추진과 조정, ④ ICT 인프라 정비 및 최신 인터넷 환경 구축, ⑤ 방송 및 \n정보유통을 위한 유무선 이설의 설치 및 사용 규제, 촉진 등을 담당함\n• 최근 일본 총무성은 로컬 5G 구현을 위한 개정된 가이드라인을 발간했으며 ‘텔레워크를 활용한 \n지역 과제 해결 사례 창출에 관한 실증 사업’을 채택함 . 또 2017년부터 조직된 사이버보안 \n태스크포스 연구 결과를 기반으로 ICT 사이버보안 종합대책 2023 초안을 마련함\n[표 2] 일본 총무성 (MIC)\n구분 내용\n주요 인사마츠모토 고메이 \u3000\n(松本\u3000剛明)\n와타나베 효이치\n(渡辺\u3000孝⼀)\n총무대신 총무부대신\n주요 소식로컬 5G 구현을 위한 \n개정된 가이드라인 발간‣ 로컬 5G 도입 촉진을 위한 지침 제정\n‣ 유연한 운영을 위해 구현 지침 개정\n‘텔레워크를 활용한 지역 과제 해결 사례 \n창출에 관한 실증 사업’ 채택‣ 컨소시엄을 통해 24년 3월까지 실시\n‣ 지방 근무 관련 텔레워크 이용 사회 실현 \n목적\nICT 사이버보안 종합대책 2023 ‣ 초안 의견 수렴 및 확정 대책 발표\n‣ 사이버보안 보장 대책 추진 예정\n주요\n산하 조직\n출처 : 일본 총무성',
 'q4': '7 Ⅰ. ICT 국가 산업 현황\n 2.ICT 정부기구\n  ② 문부과학성 (MEXT)\n 일본 문부과학성 (MEXT)\n• 일본 문부과학성 (Ministry of Education, Culture, Sports, Science and Technology) 은 \n교육, 문화, 스포츠 및 과학기술의 종합적인 진흥 등을 담당하는 중앙행정기구임\n• 문부과학성의 ICT 관련 역할은 ① 정부의 연구 개발계획 , 종합과학기술회의에 의한 \n과학기술개발의 집행, ② 과학기술 기본정책의 기획, 입안, 추진과 조정, ③ 정보통신 분야 \n연구개발의 추진 및 평가, ④ 과학기술 시스템의 개혁을 위한 방안을 마련할 수 있는 권한 보유 \n등이 꼽힘\n• 최근 문부과학성은 교육 부문 DX(Data experience) 적용에 관심을 가지며 ‘기가 스쿨(GIGA \nSCHOOL) 교무 DX’ 공표, 교육 데이터 활용에 관한 지식인 회의 진행 등을 추진함 . 이 외에도 \n기가(GIGA) 단말기 갱신을 위해 도도부현 (都道府 県)에 2,643 억 엔(약 2조 4,042 억 원) 규모의 \n기금을 조성함\n[표 3] 일본 문부과학성 (MEXT)\n구분 내용\n주요 인사모리야마 마사히토\n(盛⼭\u3000正仁)\n아베 토시코\n(あべ\u3000俊⼦)\n문부과학대신 문부과학부대신\n주요 소식기가 단말 갱신에 기금 조성‣ 도도부현에 2,643 억 엔 기금 조성\n‣ 5년에 걸쳐 단말기 갱신 및 예비 기기와 \n입출력 지원 장치의 정비 지원\n‘기가 스쿨(GIGA SCHOOL) \n교무 DX’ 공표‣ 교직원 근무 용이성 및 교육 고도화 목표\n‣ 레이와 시대 일본 교육 기반으로 지지\n 교육 데이터 활용에 관한 지식인 회의‣ 교육 데이터의 효과적 활용에 대한 \n효과적인 방책 검토\n‣ 유튜브를 통한 라이브 전달 방식 채택\n주요\n산하 조직\n출처 : 일본 문부과학성',
 'q5': '8 Ⅰ. ICT 국가 산업 현황\n 2.ICT 정부기구\n  ③ 경제산업성 (METI)\n 일본 경제산업성 (METI)\n• 일본 경제산업성 (Ministry of Economy, Trade and Industry) 은 경제활력을 위한 정책 수립 \n및 실행과 산업 및 기업의 육성을 담당하는 부처임\n• ICT 과학기술과 관련해서 경쟁력 있는 산업 및 기업의 육성 및 관리, 광물 자원 및 에너지의 \n안정적인 확보와 효율적인 유통관리 , 경제 동향 모니터링 , 민관 협력 연구개발의 추진 및 평가 \n등의 업무를 수행함\n• 최근 경제산업성은 서비스 로봇의 안전한 작동을 위한 국제 표준을 발표했으며 , EU EPA와 \n‘데이터의 자유로운 흐름’ 조항에 합의했으며 , 국토부와 2021년부터 협업한 프로젝트에 따라 \n일본 최초로 레벨 4 자율주행 모빌리티 서비스를 시작함\n[표 4] 일본 경제산업성 (METI)\n구분 내용\n주요 인사사이토 켄\n(齋藤\u3000健)\n이와타 카즈치카\n(岩⽥\u3000和親)\n경제산업대신 경제산업부대신\n주요 소식서비스 로봇의 안전한 작동을 위한 \n국제 표준 발표‣ 경제산업성 제안을 토대로 ISO에서 발표\n‣ 서비스 업계 노동력 부족 문제 극복 목적 \n 일본-EU EPA, \n‘데이터의 자유로운 흐름’ 조항 합의‣ 유럽 무역 위원과 만남 진행\n‣ 협정 개정안의 조기 서명에 필요한 \n절차를 가속화 하는데 동의 \n일본 최초 레벨 4 \n자율주행 모빌리티 서비스 시작‣ 국토부와 2021년부터 프로젝트 진행\n‣ 도로교통차량법에 따라 자동운전 \n차량으로 승인\n주요\n산하 조직\n출처 : 일본 경제산업성',
 'q6': '9 Ⅰ. ICT 국가 산업 현황\n 2.ICT 정부기구\n ④ 디지털청 (デジタル 庁) \n 일본 디지털청 (Tデジタル 庁)\n• 디지털청 (Digital Agency) 은 2021년 9월 발족되었으며 디지털 시대의 민관 인프라를 단기간인 \n향후 5년 이내에 만들어내는 것을 목표로 함. 내각부 직속조직으로 여러 부처에서 담당하던 \n디지털 관련 업무를 일원화하고 국가, 지자체 등 정보시스템을 총괄하는 부처로 자리매김할 \n예정임\n• 일본 디지털청은 최근 스마트폰용 전자증명서 탑재 서비스 출시, 마이넘버 카드 사용법 공개, \n재해 예방 환경 정비 추진 등 정책을 실행함\n \n[표 5] 일본 디지털청 (デジタル 庁)\n구분 내용\n주요 인사고노 타로\n(河野 太郎)\n이시카와 쇼마사\n(⽯川 昭政)\n디지털대신 디지털부대신\n주요 소식스마트폰용 전자증명서 탑재 서비스‣ 마이넘버 카드 소유자가 탑재 신청 가능\n‣ 스마트폰 전자증명 서비스 순차적 확대\n마이넘버 카드 사용법 공개‣ 라이프 스테이지 별 사용 방법 제시\n‣ 2024년도 중 마이넘버 카드와 운용 \n라이선스를 통합할 예정\n재해 예방 환경 정비 추진‣ 재해 예방을 위한 데이터 활용 강조\n‣ 재난 예방 아키텍처 설계와 데이터 연계 \n플랫폼 구축 목표\n주요\n산하 조직\n출처 : 일본 디지털청 홈페이지',
 'q7': '10 Ⅰ. ICT 국가 산업 현황\n 3.ICT 주요정책\n  ① 생성형 AI 서비스 사용에 관한 지침 \n 일본 개인정보위원회 , 생성형 AI 사용 지침 공개\n• 2023년 6월 2일, 일본 개인정보보호위원회가 ‘생성형 AI 서비스 사용에 관한 지침을 발표함\n• 해당 지침은 구체적인 법 위반을 지적하고 있지는 않으나 , 생성형 AI 서비스를 이용 또는 기계 \n학습을 실행하는 기업, 일반 사용자가 유의해야 할 점을 상세하게 제시함\n• 챗GPT(ChatGPT) 개발 기업 오픈에이아이 (OpenAI) 에 대해서는 별도의 지침이 행해지고 있어 \n이와 관련된 자료도 공개됨\n• 개인정보위원회는 지침을 팜플렛 형식으로 정리하여 웹사이트에 공개함 . 여기에는 개인정보 취급 \n사업자 및 행정기관 등에서 입력하는 정보가 생성형 AI 서비스의 학습데이터로 이용되는 경우에 \n유의해야 할 점들을 제시함\n- 개인정보를 포함한 데이터를 제3자에게 제공하는 경우 본인의 사전 동의 필요\n- 보유한 개인정보를 이용·제공하는 경우에는 특정 이용 목적에 한정\n[표 6] ‘생성형 AI 서비스 사용에 관한 지침’ 주요 내용\n구분 내용\n이용 목적 내에서의 \n활용  ▶ 개인정보 취급 사업자가 생성형 AI 서비스에 개인정보를 포함하는 프롬프트를 입력 \n시, 해당 개인정보 관련 특정 이용 목적을 달성하는데 필요한 범위 내에 있음을 \n충분히 확인 필요\n▶ 생성 AI 서비스에 개인정보를 포함한 프롬프트를 입력하여 개인정보로서의 답변을 \n얻는 경우, 이용 목적을 특정할 필요가 존재(개인정보보호법 17조1항)\n▶ 개인정보를 프롬프트로 입력하는 목적이 이용 목적 범위 외에 있을 경우 가명 정보 \n제도를 이용하여 이용 목적 변경 고려\n생성형 AI 서비스 \n제공 사업자가 기계 \n학습에 이용하지 \n않는 것 확인▶ 동의를 얻은 개인정보를 생성형 AI 서비스에 입력하고 , 프롬프트에 대한 응답 결과 \n출력 이외의 목적으로 취급되는 경우 개인정보보호법 규정 위반 가능성 존재\n▶ 개인정보 프롬프트를 입력하는 경우에는 생성형 AI 서비스를 제공하는 사업자가 개인 \n데이터를 기계 학습에 이용하지 않는 것 등 충분히 확인 필요\n기계 학습을 적용할 \n경우의 제안 ▶ 생성형 AI 서비스 제공 사업자가 본인의 동의를 얻지 않은 민감 정보를 획득하는 것 \n경고\n▶ 예외 사항을 제외하고 , 인터넷을 통해 민감 정보를 획득할 시에도 본인의 동의 필요\n▶ 생셩형 AI 서비스 제공자는 개인정보 사용의 목적을 공지할 필요 존재 \n출처 : ushijima-law',
 'q8': '11 Ⅰ. ICT 국가 산업 현황\n 3.ICT 주요정책\n  ② AI 학습 데이터 제공 촉진을 위한 액션플랜 ver1.0\n 일본 AI 모델 성능 향상을 위한 액션플랜\n• 2023년 11월 일본 내각부는 AI 모델 성능 향상을 위해 정부가 보유한 안전･안심 데이터를 AI \n개발자에게 AI 학습 데이터로 제공하여 개발할 수 있도록 액션플랜을 공개함\n[표 7] 액션플랜별 목표 및 대응 \n1.정부 등이 보유한 데이터를 AI 학습 데이터로 제공하는 것에 관한 홍보\no 목표: 다양한 기회를 이용하여 정부 등이 보유한 데이터의 AI 학습 데이터 제공 촉진에 대해 홍보하고 , 일본의 AI \n모델 개발력 강화에 기여\no 노력: - (내각부 , 디지털청 ) 정부에 등록된 2만 2천여 개의 데이터 세트 등을 소개하는 e-Gov 데이터 포털 링크를 AI \n전략회의 , AI 전략팀 홈페이지 등에 게재 \n-정부 등이 보유한 데이터에 대해 e-Gov 데이터 포털에 등록하도록 관계 부처에 요청\n-AI 관계자가 모이는 행사에서 e-Gov 데이터 포털, AI Japan 의 데이터 포털, 내각부 커뮤니케이션 창구 홍보\n-(관계 부처 등) 국립연구개발법인이 이용가능한 데이터 중 다운로드 가능한 URL 목록화 , 국립연구소 웹사이트에 게재\n2.AI 개발자를 위한 커뮤니케이션 창구 마련\no 목표: AI 개발자들의 AI 학습 데이터 관련 상담(수요) 접수 및 대응, 사업자의 요구사항 등을 취합하여 향후 정책 \n검토에 기여\no 노력: - (내각부 ) AI 개발자를 위해 전문성이 높은 직원으로 구성된 커뮤니케이션 창구를 내각부에 개설, AI 학습 \n데이터 제공 등을 희망하는 자의 상담(수요) 등을 접수하고 관계 부처와 연계하여 대응\n-(내각부 , 관계부처 ) 관계부처 및 유관기관에도 유사한 창구 개설을 촉구\n3.기계 판독이 불가능한 데이터 형식 변환\no 목표: AI 학습용 데이터로 필요한 데이터에 대해 기계 판독이 불가능한 PDF나 JPEG 형식 등의 데이터를 기계 \n판독이 가능한 텍스트나 HTML 형식으로 변환\no 노력: - (내각부 , 디지털청 ) AI 전략팀 산하에 데이터 PT 설치, 기계판독 가능한 형태로의 데이터 전환을 정부 차원으로 \n노력\n-(데이터 PT, 국립인쇄국 ) 내각부 사업으로 공개 데이터를 기계 판독 가능한 형식으로 변환을 시도, 다른 부처 등이 \n협력할 수 있는 사례와 구체적인 추진 방법 검토\n-시범 결과를 기반으로 중장기적인 데이터 형식 변환의 추진 방식, 체제, 비용 등의 규칙 검토 및 사업 체계 구축\n-(데이터 PT, 관계부처 ) 기계 판독이 불가능한 데이터를 분류 및 정리하여 목록화\n4.접근이 제한된 데이터를 적격 신청자에게 신속하게 제공\no 목표: AI 학습 데이터로 필요한 데이터에 대해 접근 제한 여부를 파악하고 , 접근가능한 경우 적격 신청자에게 신속하게 \n제공\no 노력: - (총무성 ) 시범사례로 NICT가 보유하고 있는 일본어 데이터에 대해 연내 공동연구 형태로 제공 검토 중\n-(데이터 PT, 관계부처 ) AI 학습 데이터로서의 수요 데이터에 대해 접근 가능 여부를 검토\n-접근이 가능한 경우 접근에 필요한 조건 및 서류 등을 수립하여 적격 신청자에게 신속 제공\n5.정부도 AI 학습 시행\no 목표: 업무 효율화 , 서비스 향상, 보다 창의적인 업무에 대한 도전(정책적 문서안 작성 등)\no 노력: - (디지털청 ) 정부도 공공기관이 보유한 데이터 등을 활용해 AI 학습 시도\n-(관계부처 ) 정부가 관여하는 프로젝트나 사업에서 AI 학습을 실시하는 경우, AI 학습 데이터 관련 과제와 그 해결 방안 \n등에 관한 지식 집약\n출처 : 일본 내각부',
 'q9': '12 Ⅰ. ICT 국가 산업 현황\n 3.ICT 주요정책\n  ③ 반도체 ･디지털 산업전략 개정안\n 고도의 디지털 사회 실현 목표\n• 일본 경제산업성 (METI) 은 2023년 5월 ‘반도체 ･디지털 산업전략 ’을 발표함 . 해당 전략은 반도체 , \n디지털 인프라 , 디지털 산업의 향후 정책 방향을 검토함\n• 2021년 6월 반도체 ･디지털 산업전략을 공표한 지 2년이 경과 되었으며 , 러･우 사태로 경제 \n안보의 중요성 및 디지털화 ･환경 관련 대응 필요성 증대되면서 반도체 ･디지털 산업전략을 \n개정함\n• 전략은 디지털 기반을 구축함으로써 저출산 ･고령화 사회에서 DX, GX를 달성하는 동시에 \n순환경제사회 , 회복 탄력성이 높은 사회를 구축하여 고도의 디지털 사회 실현을 목표로 함\n• 해당 전략은 종합 정책과 개별 정책으로 나뉨. 종합 정책은 ▲반도체 ･이차전지 등 글로벌 공급망 \n안정화를 위한 대응력 강화, ▲차세대 기술 개발 및 상용화를 위한 자본 강화 방안 지원 검토가 \n고안됨 . 개별적으로는 ▲반도체 분야, ▲정보처리 분야, ▲고도 정보통신 ·인프라 , ▲이차전시 \n분야에 대한 전략이 제시됨\n[표 8] 반도체 ･디지털 산업전략 개별 전략\n구분 내용\n반도체 분야 ▶ 2030년까지 일본 내 반도체 생산 매출액 15조엔 이상 달성\n정보처리 분야▶ 정보처리기반 정비를 통한 산업기반 구축\n- 제조 및 금융, 탄소 중립 등 다양한 분야의 고도화를 위한 필수 인프라에 해당\n- 산업기반 구축 위해 사용자 및 정보처리기반 개발 커뮤니티에서 추진하고자 하는 \n목표·방향성을 구체 및 공유를 통해 부족한 기술･노하우 등 해결\n▶ 생성형 인공지능 산업전략\n- 생성형 AI 개발･제공･이용과 관련한 사업자용 가이드라인 정비\n- 생성형 AI 활용을 통한 기업 DX 모범사례 발굴\n- 생성형 AI 활용 인재육성방안 검토\n고도 정보통신 ·인프라 \n분야▶ 디지털 인프라 정비\n- 도쿄권･오사카권을 보완하는 홋카이도 , 규슈 지역 등 제3, 4의 핵심거점 정비\n- 지역의 분산형 데이터센터 건설 등 컴퓨터 자원 정비\n- 고성능 반도체 디바이스 활용을 포함한 일본 통신시스템의 에너지 절약 성능 강화 등을 위한 \n국제경쟁력 강화 필요\n이차전지 분야▶ 2030년까지 제조 능력을 확립하여 개발･생산을 선도하는 세계 거점 구축 실현\n- (개발･생산 거점) 배터리 및 자동차 업체의 이차전지 양산 계획과 소재 및 제조장치의 집적화 \n추진 중\n- (인재육성 거점) 간사이 인재육성 등 컨소시엄 및 산업종합연구소 간사이 센터를 중심으로 한 \n산학관 협력 추진 중\n출처 : 일본 경제산업성',
 'q10': '13 Ⅰ. ICT 국가 산업 현황\n 4.ICT 주요법령 및 규제\n  ① 산업경쟁력 강화법 (개정)\n 자국 산업 관련 투자 강화 정책\n• 일본 경제산업성 (METI) 은 2023년 12월 산업경쟁력 강화법 개정에 대해 논의한 자료를 발표함 . \n산업경쟁력 강화법 개정 방향에 대한 정책적 지원 방안은 이하와 같음\n1) 국내 투자 촉진\n① 전략 분야 국내 생산 촉진\n-정책 분야 중 국가적으로 장기 투자가 필수적인 투자 분야를 선정·집중 지원하는 방안 검토\n-기반 강화 제품의 생산·판매에 대한 투자세액감면 조치 방안 마련 검토\n-5가지 전략 분야로는 ▲반도체 , ▲전동차 , ▲그린 스틸, ▲그린 케미칼 , ▲SAF가 선정\n② 이노베이션 거점 세제(이노베이션 박스 세제)\n-일본에서 스스로 연구 개발한 특허권 등 지식재산에서 발생하는 소득에 대해 우대하는 \n이노베이션 거점 세제 신설 검토\n-지식재산의 라이선스 및 양도에 의한 오픈 이노베이션 등 기업이 개발한 지식재산의 사업화에도 \n인센티브를 부여하는 방안 검토\n-생성형 AI 등 소프트웨어의 저작권도 대상에 포함하는 방안 검토\n2) 혁신 및 투자 대상 사업 확대\n① LPS 투자 대상 사업 확대\n-LPS 투자 대상 사업에 암호자산 취득 등 추가. 웹 3.0(Web3.0) 관련 사업을 실시하는 \n스타트업의 자금조달 방안 검토\n-LPS의 해외 투자 상한 규제 철폐. 해외 투자자로부터의 자금 유입 및 해외 진출 스타트업의 \n성장을 촉진하는 방안 검토\n② 특정 신수요 개척사업 계획 인정제도 신설\n-기업 및 대학 등 연구기관이 공동으로 실시하는 연구개발에 대해 표준화와 지식재산을 \n유기적으로 활용하는 오픈 앤 클로즈 (Open & Close) 전략 수립 활동 촉진 위한 계획안정제도 \n신설\n• 한편 2023년 12월 산업구조심의회는 스타트업이 투자 펀드로부터 출자를 받을 때 주식 등이 \n아니라 암호자산을 전달할 수 있도록 하는 규제 완화 정책을 제안함 . 이는 스타트업에 대한 해외 \n투자를 장려하기 위한 방안임',
 'q11': '14 Ⅰ. ICT 국가 산업 현황\n 4.ICT 주요법령 및 규제\n  ② 첨단 반도체 제조 장비 수출 규제\n 대중국 반도체 장비 수출 제한 정책\n• 일본 정부는 2023년 3월, 반도체 제조 장비 23개 품목에 대한 수출을 제한함 . 수출 제한에 \n포함되는 품목은 반도체 세정 장비, 박막증착 장비, 열처리 등 칩 제조용 품목이 포함됨 . 또 \n극자외선 (EUV) 관련 제품 제조 장비와 메모리 소자의 3차원 적층을 위한 시각 장비도 포함됨 \n모두 10~14nm 이하 선폭을 가진 첨단 제품을 제조하는 데 필요한 장비들임\n• 해당 조치는 2022년 10월 미국의 대중국 반도체 장비 수출 규제에 대한 후속 조치임 . 일본의 \n수출 규제는 특정 국가를 명시하지 않았으나 23개 품목에 대해선 한국, 미국 등 우호적인 42개 \n국가와 지역을 제외한 나머지 지역 수출 시 일본 기업들은 건별로 경제산업성 (METI) 의 허가를 \n받도록 하여 사실상 중국에 대한 수출이 불가능하게 됨\n • 일본은 세계 반도체 시장 장비 제조 분야에서 미국, 네덜란드와 함께 최고의 경쟁력을 가지고 \n있음. 중국은 해당 분야에서 자립할 기술력을 아직 얻지 못하고 있어 자립을 위해 막대한 투자를 \n진행하고 있는 상태임\n • 일본의 수출 규제와 관련하여 중국 상무부는 일본 정부의 조치는 수출 통제 조치의 남용이자 \n자유무역과 국제 경제·무역 규칙을 심각하게 위배하는 것으로 , 이에 대해 반대하는 입장을 \n발표하며 즉시 시정을 요구함\n[표 9] 일본 대표 EUV 업체\n기업 주요 제품/서비스 시장 입지\n도쿄일렉트론\n(Tokyo Electron)코터/개발자를 위한 EUV 기술 대량 생산 도구 시장에 중요 입지 차지\n레이저텍\n(Lasertec)검사 장비 EUV 개발로 이익 획득\n누플레어 테크놀로지\n(NuFlare Technology)광판 추적용 전자빔 장치 JEOL 과 IMS의 제휴로 경쟁\n기가포톤\n(Gigaphoton)노광기용 광원 시장점유율 회복 위해 재기 노력\n출처 : displaydaily',
 'q12': '15 Ⅰ. ICT 국가 산업 현황\n 5.ICT 주요기업\n 일본 ICT 관련 기업 1위, 도요타\n• 일본의 대표적 자동차 기업 도요타 (Toyota) 의 매출액은 2,966 억 1,000 만 달러(약 395조 845억 \n원)로 일본 ICT 관련 기업 중 1위를 차지함\n• 전자 장비 기업 미쓰비시 (Mitsubishi Corporation) 와 자동차 기업 혼다(Honda) 가 각각 2, 3위\n를 차지함\n 일본 전통 기업들 강세\n• 일본은 설립된 지 100년 가까이 된 전통 기업들이 여전히 강세를 보이고 있음. 히타치 (Hitachi),  \n미쓰비시 전기(Mitsubishi Electric) 등 기업은 1920년대에 설립되었으며 , 그 외의 기업들 또한 \n반세기 이상의 시기 동안 발전을 이어오고 있음\n[표 10] 일본 주요 ICT 기업 \n순위 기업명 매출액 (10억 달러) 사업 분야\n①Toyota\n(www.toyota.com)296.61 자동차\n②Mitsubishi Corporation\n(www.mitsubishielectric.com)147.18 전자 장비\n③Honda\n(www.honda.com)132.11 자동차\n④NTT, Nippon Telegraph&Telephone\n(group.ntt)95.11 통신\n⑤Sony\n(www.sony.co.kr)88.46 전자 장비\n⑥Nissan\n(www.nissan.co.jp)86.12 자동차\n⑦Hitachi\n(www.hitachi.com)75.06 특수산업기계\n⑧Panasonic\n(www.panasonic.co.kr)60.68 전자 장비\n⑨KDDI\n(www.kddi.com)68.69 이동통신 , 스마트폰\n⑩Softbank\n(www.softbank.jp)64.66 투자, 이동통신\n출처 : companies marketcap',
 'q13': "16 Ⅰ. ICT 국가 산업 현황\n 6.한국 협력 및 국내기업 진출사례\n 한국-일본 FTA 체결 여부\n• 한국과 일본은 2010년 1월 1일 포괄적 경제동반자협정 (CEPA) 이 발효됨\n• 2022년 1월 한국-일본 CEPA 개선 협상이 2년 반 만에 재개됨 . 해당 협상에서는 포스트 코로나 \n시대를 대비해 공급망 강화, 기후변화 , 백신, 디지털 협력 등의 이슈 관련 양국 협력 확대 \n방안을 논의해 나가기로 합의함\n 한국-일본 ICT 기관 협력 사례\n• 2023년 10월 이종호 과학기술정보통신부 장관이 일본을 방문해 총무성 , 문부과학성과 장관회담 \n진행하고 한일 간 공동연구 및 인력교류 활성화 방안 논의\n 한국-일본 ICT 기업 진출 사례\n• 전자, 디지털 치료제 , 무인 로봇, 클라우드 등 다양한 한국 ICT 사업의 일본 진출이 활발함\n[표 11] 한국-일본 협력 현황\n구분 날짜 내용\nFTA 체결여부10.01 ‣ 한국-일본 포괄적 경제동반자협정 (CEPA) 발효\n22.01 ‣ 한국-일본 CEPA 개선 협상 2년 반 만에 재개\n정부22.10 ‣ NIPA·ITSA, ‘일본 현지 바이어 발굴 행사’ 개최\n22.12 ‣ 코트라 , 일본 DX 시장 진출 위한 ‘코리아 ICT 엑스포 in 재팬’ 개최\n23.12 ‣ 이종호 과학기술정보통신부 장관 일본 방문\n기업22.10 ‣ 알서포트 , ‘재팬 IT 위크’ 참가하며 일본 화상회의 시장 공략 가속화\n22.10 ‣ 시큐아이 , 일본 전용 방화벽 제품으로 일본 IT 보안 시장 공략\n22.11 ‣ SKT, NTT 도모코와 ICT 동맹 강화\n23.01 ‣ 영남이공대 일본 IT 전공, 전원 취업\n23.01 ‣ 삼성전자 , 일본 상용망에서 ‘5G 네트워크 슬라이싱 ’ 검증\n23.02 ‣ 삼성전자 , 일본 KDDI에 '5G 코어' 솔루션 공급\n23.07 ‣ 로완, 치매 디지털 치료제로 초고령사회 일본 진출\n23.11 ‣ LS머트리얼즈 , 일본 무인 운반 로봇에 울트라 커패시터 공급\n23.12 ‣ 유니온커뮤니티 , 생체인증 클라우드 구독 서비스로 일본 시장 진출\n출처 : 주요 ICT 매체 발표 기사 취합",
 'q14': 'Ⅱ ICT 이슈 TOP 10                   16\n   ① 일본, 아시아에서 두 번째로 큰 데이터센터 허브\n   ② 일본, 자체 개발 소프트웨어로 사이버보안 강화\n   ③ 일본, Web3 산업 성장 촉진 도모\n   ④ 일본, 정부 행정 업무에 생성형 AI 도입\n   ⑤ 일본, 첫 자체 제작 양자컴퓨터 공개\n   ⑥ 일본, 6G 기술 강화 위해 협력 및 규제 완화\n   ⑦ 일본, 레벨 4 자율주행 허용\n   ⑧ 일본, 생체인식 결제 도입 증가 \n   ⑨ 일본, 행정 서비스 디지털화 노력\n   ⑩ 일본, 인재 부족으로 디지털 인력 강화에 힘써',
 'q15': '19 Ⅱ. ICT 이슈 Top10\n ①일본, 아시아에서 두 번째로 큰 데이터센터 허브\n 일본 데이터센터 시장 CAGR 5.93% 예상  \n• 일본 데이터센터 시장은 2022~2028 년 연평균 성장률 (CAGR) 5.93% 로 성장할 것이라 \n예상됨 . 아시아태평양 (APAC) 지역의 경제 강국이자 글로벌 연결의 허브로서 일본의 위상이 \n호황의 주요 원인이 된 것으로 분석됨\n• 일본 데이터센터 시장은 2028년 114억 4,000 만 달러(약 15조 2,266 억 원) 규모의 투자를 \n유치할 것으로 예상됨 . 같은 해 코로케이션 시장 매출은 38억 2,000 만 달러(약 5조 844억 \n원)에 이를 것으로 예측됨 . 리서치 앤 마켓(Research and Markets) 에 의하면 이는 일본이 \n중국과 호주에 이어 아시아태평양 지역 최고의 데이터센터 시장으로 자리 잡게 하는 가장 \n큰 규모의 투자 중 하나임\n 홋카이도 ·규슈 지역 데이터센터 보조금 검토  \n• 2023년 5월, 일본 경제산업성 (METI) 은 홋카이도과 규슈 지역의 데이터센터 건설을 \n촉진하기 위해 보조금을 제공할 것을 제안함 . 홋카이도와 규슈는 재생에너지에서 생산되는 \n전력량이 많아 전력 소비가 많은 데이터센터에 적합한 지역이라고 분석함\n• 일본 내 데이터센터의 80% 이상은 도쿄와 오사카 지역에 위치해 있음. 대규모 자연재해에 \n취약한 일본의 특성상 데이터센터의 분산화가 요구됨 . 보조금 계획으로 인한 홋카이도 , 규슈 \n지역 투자는 데이터센터 분산화에 긍정적 기여를 할 것으로 기대됨\n• 일본 국토부는 2023년 4월부터 4년간 데이터센터 보조금으로 455억 엔(약 4,095 억 910만 \n원)을 배정할 계획을 제시함\n 도쿄, 아시아의 데이터센터 허브로서 베이징에 도전  \n• 국내외 데이터 처리 수요가 급격히 증가함에 따라 도쿄에서는 데이터센터가 급증함 . 도쿄 \n지역 데이터 시설의 총 용량은 3~5년 내에 두 배로 증가해 베이징에 이어 아시아에서 두 \n번째로 큰 데이터센터 허브가 될 것으로 전망됨\n• 증대되는 안보 우려와 미-중 긴장으로 인해 글로벌 정보기술 기업 등은 중국의 도시를 \n외면하고 있음. 이에 따라 도쿄는 베이징과의 격차를 빠르게 좁히고 있다는 분석임\n• 쿠시먼앤드웨이크필드 (Cushman & Wakefield) 는 2022년 말 도쿄 광역 지역의 \n데이터센터 용량은 총 865MW 로 베이징의 절반 수준이었지만 3~5년 안에 1,970MW 에 \n도달할 전망임\n• 북미와 유라시아 사이에 위치한 일본은 메타(Meta), 구글(Google) 등 미국 IT 대기업들이 \n대규모 데이터를 옮기는 이상적인 중계국 역할을 할 수 있을 것으로 평가됨',
 'q16': '20 Ⅱ. ICT 이슈 Top10\n ②일본, 자체 개발 소프트웨어로 사이버보안 강화\n 경제산업성 , 미국 국토안보부와 소프트웨어 보안 표준 합의\n• 2023년 1월, 일본 경제산업성 (METI) 과 미국 국토안보부가 사이버보안 분야에서 국방 협력 \n강화를 위해 MOU 를 체결함\n• 양국은 중요 기반 시설의 보호 개선 및 사회 경제 활동에 대한 혼란과 기밀정보 유출의 \n위험을 줄이기 위해 정부 조달 소프트웨어에 대해 동일한 수준의 보안 표준을 확립하기로 \n합의함\n• 일본과 미국은 또한, 소프트웨어 보안 취약성을 평가하기 위한 안전 시스템 구축에 \n협력하고 , 인도 태평양 지역의 사이버 방어 역량을 강화하기 위한 파트너십 협정에 호주와 \n인도를 포함시킬 것으로 예상됨\n• 이번 MOU 체결 각서는 2022년 국가 안보 전략 개정에 따른 정부 간 최초의 사이버보안 \n협력으로서 의미를 지님. 두 전략 모두 중국, 러시아 , 북한 등의 국가들이 가하는 위협에 \n대응하여 더욱 강력한 사이버보안을 달성하는 것을 목표로 함\n  - 지난 몇 년 동안 일본과 미국의 주요 시스템은 악의적인 공격의 표적이 되어, 미국의 \nSolarWinds 해킹과 Colonial Pipeline 랜섬웨어 공격으로 인해 각각 민감한 데이터가 \n노출되고 가스 파이프라인이 중단된 바 있음\n 정부 계약 업체에 미국 사이버보안 규정 준수 요구\n• 2023년 6월, 일본이 민감 정보를 보호하기 위한 목적으로 정부 계약업체에 미국 \n사이버보안 지침을 준수하도록 요구할 계획을 발표함 . 이는 싱크탱크와 통신업체를 포함한 \n1,000 개 이상의 기업에 영향을 미칠 것으로 예상됨\n• 정부 사이버보안 전략실은 중앙 부처와 함께 독립 행정기관의 정보보안 기준을 개정해 \n외부업체에 요구되는 대책을 강화함 . 해당 기준은 2024년 3월부터 적용될 예정임\n 일본, 자체 개발 소프트웨어로 사이버 방어 강화\n• 일본은 2025년부터 자체 개발한 소프트웨어로 사이버 방어를 강화할 계획임 . 해당 \n소프트웨어는 정부 컴퓨터를 위한 새로운 시스템으로 , 공격 정보를 수집·분석함\n• 일본 정부의 신규 소프트웨어는 마이크로소프트 (Microsoft) 및 기타 기업의 기존 \n소프트웨어와 호환됨 . 이에 따라 함께 사용되며 계층화해 방어 능력을 강화할 예정임',
 'q17': '21 Ⅱ. ICT 이슈 Top10 \n ③일본, Web3 산업 성장 촉진 도모\n 일본 정부, 웹3.0 백서 발표\n• 일본 자민당 웹3.0(Web3.0) 프로젝트팀이 기시다 후미오 (岸⽥⽂雄 ) 총리의 기술 진흥 전략 \n‘쿨 재팬(Cool Japan)’ 프로젝트의 일환으로 자국 암호화폐 산업 육성을 위한 권고 사항을 \n담은 백서를 발표함\n• 일본 정부는 기업들이 과도한 세금 부담으로 인해 다른 관할권으로 이동하기 시작한 후 \n암호화폐에 대해 우호적인 환경을 조성하려고 노력해 왔음. 웹3.0 프로젝트 팀은 NFT, \n분산형 자율 조직 등에 대한 규제 제안을 공식화하기 위한 행보를 전개함 . 이 과정에서 \n일반적인 관료적 절차의 적용을 받지 않음\n• 백서는 토큰 발행자 관련 승인된 주요 면제 사항을 언급하며 세금 규정에 대한 추가 변경을 \n제안함 . 여기에는 다른 기업이 발행했으며 단기적으로 거래되지 않을 토큰을 보유하고 있는 \n기업에 대한 세금 면제가 포함됨 . 투자자들은 손실을 3년 동안 이월할 수 있도록 자체 \n평가를 허용할 것을 권고하고 , 자산이 명목화폐로 교환될 때만 암호화폐에 과세해야 한다고 \n제안함\n• 이외에도 회계 표준의 부족으로 웹3.0 기업들이 감사인을 찾는 데 어려움을 겪고 있는 점을 \n지적하며 이는 시급한 문제임을 확인함 . 각 부처와 기관은 지침을 마련하는 데 있어 \n일본공인회계사협회를 지원해야 한다고 명시함\n 일본 정부, 웹3.0 강조 \n• 일본 정부는 최근 여러 행보에서 웹3.0을 강조하며 관련 사업과 투자에 열려 있음을 \n부각하고 있음\n• 일본 기시다 후미오 총리가 고노 타로(河野 太郎) 디지털 담당 대신을 새로 임명하며 , 일본 \n정부가 웹3.0 개발을 경제 계획의 최우선 과제로 삼을 것이라는 기대가 고조됨 . 고노 타로 \n대신은 디지털청 (Digital Agency) 을 담당하게 됨. 최근 고노 타로 대신은 트위터를 통해 \n240만 명의 팔로워에게 메타버스 공간에서 사용할 수 있는 디지털 아바타를 만들어 달라고 \n요청한 바 있음\n• 2023년 5월 영국을 방문한 기시다 총리는 영국 투자자들에게 일본 정부가 웹3.0 관련 \n성장을 목표로 삼고 있다고 연설하며 메타버스 및 NFT 관련 개발을 모두 언급함\n• 일본 도쿄 국제 포럼에서 이틀간 진행된 웹X(WebX) 아시아 컨퍼런스 폐막식에서 고이케 \n유리코 (⼩池百合⼦ ) 도쿄 도지사는 영상을 통해 주최 측을 축하하고 도쿄가 글로벌 암호화폐 \n허브로 자리매김하고 있음을 강조함',
 'q18': '22 Ⅱ. ICT 이슈 Top10\n ④일본, 정부 행정 업무에 생성형 AI 도입\n 일본 정부, 행정업무에 챗GPT 기술 활용 \n• 2023년 7월, 일본 정부는 마이크로소프트 (Microsoft) 로부터 챗GPT(Chat GPT) 기반 \n기술을 제공받을 계획을 발표함 . 이용료는 연간 200만 달러(약 26억 6,200 만 원)임 \n• 일본 정부는 행정의 디지털화를 도입해 공무에 챗GPT 기술을 활용하겠다는 방침임 . 해당 \n기술은 국회 답변 초안 및 의사록 작성, 정부 통계 분석 지원 등에 시험적으로 사용됨\n• 마이크로소프트와 일본은 국가 안보 관점에서 기밀정보를 취급할 수 있도록 일본 내에 전용 \n설비를 두기로 결정함 . 정부 이용을 위해 AI에 학습시켜야 하는 대량의 행정정보는 국외로 \n반출하기 어렵기 때문임 . 마이크로소프트가 전용 설비 등 해외에 거점을 두고 기술 서비스를 \n전개하는 것은 유럽 외의 국가 중 일본이 유일함\n• 마이크로소프트는 협력을 통해 일본어 데이터를 축적하고 해당 언어의 정밀도를 높일 \n계획임 . 또한 정부 계약을 발판으로 일본 민간 기업에 대한 서비스를 확대할 수 있을 것으로 \n기대됨\n 사미하라시 , 지자체 최초 업무용 AI 도입\n• 2023년 10월, 일본 사가미하라시가 일본전기주식회사 (NEC) 와 협정을 맺고 국산 AI 서비스 \n도입을 위해 현재 검증 절차를 진행함 . 일본에서 자국 AI 시스템의 도입 사례는 \n사가미하라시가 최초임\n• 사가미하라시는 AI를 문서 작성 및 요약과 아이디어 생성 등에 활용할 예정임 . 일본 전문 \n용어 대응에 불충분하다는 평가를 받는 챗GPT와 달리 일본산 AI는 응답의 정확성이 \n상대적으로 높을 것으로 기대됨\n• 행정 업무에 생성형 AI 기술을 활용하는 것에 대한 개인정보의 유출 위험의 불안이 남아 \n있으나 일본산 AI 서비스는 데이터센터를 일본 내에 설치하기 때문에 정보를 일본 내에서 \n관리할 수 있다는 장점도 존재함',
 'q19': '23 Ⅱ. ICT 이슈 Top10 \n ⑤ 일본, 첫 자체 제작 양자컴퓨터 공개\n 경제산업성 , 양자 컴퓨터 클라우드 이용 확대에 42억 엔 지원\n• 2023년 4월, 일본 경제산업성 (METI) 은 양자컴퓨터를 이용한 클라우드 이용 확대를 위해 \n42억 엔(약 378억 84만 원)을 조성함 . 이를 통해 양자 기술을 이용한 클라우드 인프라 \n구축을 가속화 할 전망임\n• 경제산업성은 향후 5년간 도쿄 대학, 도요타자동차 등으로 구성하는 산학협의회에 자금을 \n원조해 첨단 기계의 도입을 뒷받침할 계획임 . 보조금을 이용해 비트 수가 127인 고성능 \n모델을 도입함\n 리켄, 일본 최초의 양자 컴퓨터 가동\n• 2023년 3월 일본 리켄(Riken) 은 자체 제작한 일본 최초의 양자컴퓨터의 가동을 시작함 . \n리켄은 양자컴퓨터의 가동을 시작하고 클라우드를 서비스를 통해 대학 및 연구기관에서 \n사용할 수 있도록 지원함 . 리켄이 공개한 양자컴퓨터는 절대 영도 가까이 온도를 낮춰 \n전기저항을 없앤 초전도 환경에서 운영하며 성능은 64 양자 비트임\n• 2023년 10월에 리켄은 후지쯔와 공동으로 개발한 두 번째 양자컴퓨터를 공개함 . 후지쯔와 \n리켄이 공동 개발한 64큐비트 양자컴퓨터는 사이타마현 와코시에 있는 양사의 연계 센터에 \n설치하여 제공함 . 해당 양자컴퓨터는 극저온으로 냉각한 초전도 회로로 계산하는 범용 \n방식의 기술을 적용함\n 일본 공동 연구 그룹, 오사카대학에서 일본 세 번째 양자컴퓨터 출시\n• 2023년 12월, 오사카대학교 양자정보 및 양자생물학세터 , 리켄(RIKEN), 산업기술 \n종합연구소 첨단반도체연구센터 등이 포함된 공동 연구 파트너 컨소시엄은 오사카 대학에서 \n일본의 세 번째 초전도 양자컴퓨터 개발에 성공했다고 발표함\n• 새로 개발된 초전도 양자컴퓨터는 리켄이 제공하는 64큐비트 칩을 사용하며 , 냉장고를 \n제외한 대부분의 부품을 일본산 부품으로 사용하여 일본산 부품의 성능을 확인하는 등 \n테스트베드로 활용할 예정임\n• 연구 그룹은 양자컴퓨터가 기계학습 및 실용적인 양자 알고리즘 개발 분야의 발전을 \n촉진하고 , 재료 및 약물 개발 분야에서 새로운 사용 사례를 발굴할 수 있게 하며, 환경 \n문제를 완화하기 위한 최적화 문제 해결에 기여할 것으로 기대됨',

In [15]:
dataset["queries"]

{'q0': '일본의 데이터센터 허브 규모는 아시아에서 어느 정도인가요?',
 'q1': '일본에서 정부 행정 업무에 도입된 새로운 기술은 무엇인가요?',
 'q2': 'ICT 정부기구는 어떤 역할을 수행하며, 그 중요성은 무엇인가요?',
 'q3': '한국의 ICT 주요기업에는 어떤 기업들이 있으며, 그들의 특징은 무엇인가요?',
 'q4': '일본의 인터넷 사용자 비중과 고정 광대역 가입자 비중은 각각 얼마인가요?',
 'q5': '기시다 총리는 어떤 경제 정책에 중점을 두고 있으며, 그 중 하나로 어떤 논의에 속도를 내고 있나요?',
 'q6': '일본 총무성(MIC)의 주요 역할 중 하나는 무엇인가요?',
 'q7': '최근 일본 총무성이 발간한 가이드라인의 목적은 무엇인가요?',
 'q8': '일본 문부과학성(MEXT)의 주요 역할 중 하나로, 과학기술 개발을 담당하는 기구는 무엇인가요?',
 'q9': '최근 문부과학성이 추진하고 있는 교육 부문 DX(Data experience) 관련 사업의 이름은 무엇인가요?',
 'q10': '일본 경제산업성이 최근 발표한 국제 표준의 목적은 무엇인가?',
 'q11': '일본에서 레벨 4 자율주행 모빌리티 서비스가 시작된 프로젝트는 어떤 부처와 협업하여 진행되었는가?',
 'q12': '일본 디지털청의 주요 목표는 무엇인가요?',
 'q13': '일본 디지털청에서 추진하고 있는 정책 중 하나는 무엇인가요?',
 'q14': '생성형 AI 서비스 사용 시 개인정보 취급 사업자가 유의해야 할 사항은 무엇인가요?',
 'q15': '일본 개인정보보호위원회가 발표한 생성형 AI 서비스 사용 지침의 주요 내용은 어떤 것들이 있나요?',
 'q16': '일본 내각부가 AI 모델 성능 향상을 위해 추진하는 주요 정책은 무엇인가요?',
 'q17': 'AI 학습 데이터 제공 촉진을 위한 액션플랜에서 기계 판독이 불가능한 데이터의 변환을 위해 어떤 노력이 이루어지고 있나요?',
 'q18': '일본의 반도체 및 디지털 산업 전략에서 2030년까지 달성하고자 하는 반도체 생산 매출액은 얼마인가?',
 'q19': '일본의 정보처리 분야 전략에서 생성형 인공지능과 관련하여 추진되는 주요 내용은 무엇인가?',
 'q20': '일본의 산업경쟁력 강화법 개정에서 중점적으로 지원하는 전략 분야는 무엇인가요?',
 'q21': '이노베이션 거점 세제의 목적과 포함될 가능성이 있는 소프트웨어 유형은 무엇인가요?',
 'q22': '일본이 2023년 3월에 수출을 제한한 반도체 제조 장비의 주요 품목은 무엇인가요?',
 'q23': '중국 상무부는 일본의 수출 규제에 대해 어떤 입장을 밝혔나요?',
 'q24': '일본의 ICT 관련 기업 중 매출액이 가장 높은 기업은 무엇인가요?',
 'q25': '일본의 전통 기업 중 설립된 지 100년 이상 된 기업의 예시는 무엇이 있나요?',
 'q26': '한국과 일본의 포괄적 경제동반자협정(CEPA)은 언제 발효되었나요?',
 'q27': '2023년 10월, 한국의 어떤 정부 기관 장관이 일본을 방문하여 협력 방안을 논의했나요?',
 'q28': '일본이 아시아에서 두 번째로 큰 데이터센터 허브로 자리 잡은 이유는 무엇인가요?',
 'q29': '일본에서 생성형 AI가 도입된 정부 행정 업무의 주요 목적은 무엇인가요?',
 'q30': '일본 데이터센터 시장의 예상 연평균 성장률(CAGR)은 얼마인가요?',
 'q31': '홋카이도와 규슈 지역에 데이터센터 건설을 촉진하기 위한 일본 정부의 계획은 무엇인가요?',
 'q32': '일본이 미국과 체결한 사이버보안 협력 MOU의 주요 목적은 무엇인가요?',
 'q33': '일본 정부가 2023년 6월 발표한 계획은 어떤 기업에 영향을 미치며, 그 내용은 무엇인가요?',
 'q34': '일본 정부가 웹3.0 산업 성장을 촉진하기 위해 발표한 백서의 주요 내용은 무엇인가요?',
 'q35': '기시다 후미오 총리가 임명한 디지털 담당 대신은 누구이며, 그가 맡은 역할은 무엇인가요?',
 'q36': '일본 정부는 행정 업무에 어떤 기술을 도입하기로 계획하고 있으며, 그 이용료는 얼마인가요?',
 'q37': '사가미하라시는 어떤 AI 서비스를 도입하기 위해 어떤 회사와 협정을 맺었으며, 이 서비스의 도입 사례는 일본에서 어떤 의미를 가지나요?',
 'q38': '일본이 양자컴퓨터 클라우드 이용 확대를 위해 조성한 지원금의 금액은 얼마인가?',
 'q39': '리켄이 공개한 첫 번째 양자컴퓨터의 성능은 몇 양자 비트인가?',
 'q40': '일본의 이동통신사 NTT와 KDDI가 협력하여 개발하고자 하는 6G 기술의 주요 목표는 무엇인가요?',
 'q41': '일본 자민당이 NTT의 규제를 완화하려는 이유는 무엇인가요?',
 'q42': '일본에서 레벨 4 자율주행차의 공공 도로 운행을 허용하기 위해 어떤 법이 개정되었나요?',
 'q43': '자율주행 서비스 제공업체가 준수해야 하는 주요 허가 요건은 무엇인가요?',
 'q44': '일본에서 생체인식 결제 시스템을 도입하는 주요 이유는 무엇인가요?',
 'q45': '서일본 여객 철도가 시범 운영 중인 생체인식 발권 시스템의 주요 기능은 무엇인가요?',
 'q46': '일본에서 전자 처방전 도입의 주요 이점은 무엇인가요?',
 'q47': '일본 법무부가 형사 절차의 디지털화를 위해 도입할 계획인 전자 문서는 어떤 것들이 있나요?',
 'q48': '일본 정부는 디지털 인력 강화를 위해 어떤 계획을 세우고 있나요?',
 'q49': '일본 경제산업성이 생성형 AI 인재 육성을 위해 마련한 지침의 주요 내용은 무엇인가요?',
 'q50': '2023년의 Global Innovation Index를 발표한 기관은 어디인가요?',
 'q51': '일본의 반도체 및 디지털 산업 전략에 대한 문서를 발행한 정부 부처는 무엇인가요?',
 'q52': '정보통신산업진흥원이 발행한 원고의 발행일자는 언제인가요?',
 'q53': '원고를 인용하거나 활용할 때 지켜야 할 이용 규칙에는 어떤 것들이 포함되나요?'}

In [16]:
dataset["relevant_docs"]

{'q0': {'q0'},
 'q1': {'q0'},
 'q2': {'q1'},
 'q3': {'q1'},
 'q4': {'q2'},
 'q5': {'q2'},
 'q6': {'q3'},
 'q7': {'q3'},
 'q8': {'q4'},
 'q9': {'q4'},
 'q10': {'q5'},
 'q11': {'q5'},
 'q12': {'q6'},
 'q13': {'q6'},
 'q14': {'q7'},
 'q15': {'q7'},
 'q16': {'q8'},
 'q17': {'q8'},
 'q18': {'q9'},
 'q19': {'q9'},
 'q20': {'q10'},
 'q21': {'q10'},
 'q22': {'q11'},
 'q23': {'q11'},
 'q24': {'q12'},
 'q25': {'q12'},
 'q26': {'q13'},
 'q27': {'q13'},
 'q28': {'q14'},
 'q29': {'q14'},
 'q30': {'q15'},
 'q31': {'q15'},
 'q32': {'q16'},
 'q33': {'q16'},
 'q34': {'q17'},
 'q35': {'q17'},
 'q36': {'q18'},
 'q37': {'q18'},
 'q38': {'q19'},
 'q39': {'q19'},
 'q40': {'q20'},
 'q41': {'q20'},
 'q42': {'q21'},
 'q43': {'q21'},
 'q44': {'q22'},
 'q45': {'q22'},
 'q46': {'q23'},
 'q47': {'q23'},
 'q48': {'q24'},
 'q49': {'q24'},
 'q50': {'q25'},
 'q51': {'q25'},
 'q52': {'q26'},
 'q53': {'q26'}}

- 이제 dataset 을 InformationRetrievalEvaluator에 전달합니다.

In [17]:
# 검증 데이터셋에서 코퍼스(전체문서), 쿼리, 기리고 각 쿼리와 관련된 문서 가져오기
corpus = dataset["corpus"]
queries = dataset["queries"]
relevant_docs = dataset["relevant_docs"]

evaluator = InformationRetrievalEvaluator(
    queries=queries, corpus=corpus, relevant_docs=relevant_docs
)

- 테스트 데이터를 이용하기 위해 평가하기 위한 준비가 끝났습니다.
- 파인튜닝을 진행하고 학습 전, 후 모델에 대해 평가를 진행해보겠습니다.

## 3.6 모델 학습하기

- 실제로 모델을 학습시켜 봅시다. 데이터 양이 적기 때문에 많은 학습이 필요하지는 않습니다.
- 학습 횟수를 의미하는 EPOCHS값을 2로 설정합니다.
- 학습 데이터 52개에 대해 총 2회 반복하여 학습합니다.

In [18]:
EPOCHS = 2

# W&B(WandB, Weights and Biases) 로깅 비활성화
# W&B는 학습 과정을 실시간으로 추적하고 시각화할 수 있는 도구
os.environ["WANDB_DISABLED"] = "true"

# 학습 초기에 학습률을 점진적으로 증가시키는 단계 수 설정
# 전체 학습 단계의 10%를 워밍업으로 사용
warmup_steps = int(len(loader) * EPOCHS * 0.1)

# 모델 학습
model.fit(
    train_objectives=[(loader, loss)],  # 학습 데이터 로더와 손실 함수 설정
    epochs=EPOCHS,  # 총 에포크 수
    warmup_steps=warmup_steps,  # 워밍업단계
    output_path="exp_finetune",  # 학습된 모델 저장 경로
    show_progress_bar=True,  # 학습 진행률 표시 여부
)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

c:\workspace\python\rag_master\.venv\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

- 코드에서 os.environ["WANDB_DISABLED"] = "true" 는 학습 시 로그를 기록하는 모듈을 여기서는 사용하지 않는다는 의미입니다.
- 학습 과정을 시각화하지 않고 간단히 진행할 때 유용합니다.
- warmup_steps는 학습 초기에 학습률을 점진적으로 증가시키는 단계 수 입니다.
- 데이터 로더의 길이와 에포크 수를 곱한 값의 10%를 사용하므로, 전체 학습의 초반 10%는 학습률이 서서히 증가하게 됩니다.
- 실제 학습은 model.fit() 함수를 통해 이루어집니다.
- 준비한 데이터 로더와 손실 함수를 연결합니다.
- output='exp_finetune'은 파인튜닝된 모델을 exp_finetune 디렉터리에 저장한다는 의미입니다.

# 3.7 검색 성능 평가 지표

- InformationRetrievalEvaluator 에서 사용하는 총 6개의 주요 평가 지표를 간단히 정리합니다.

### 1. Accuracy

- Accuracy는 정답이 상위 몇 개의 검색 결과 안에 포함되었는지를 평가하는 지표입니다.
- 중요한 점은 정답이 포함되기만 하면 성공으로 간주한다는 것입니다.
- 예를들어 Accuracy@5가 0.92라는 값은 전체 질문중 약 92%에서 상위 5개의 결과 안에 정답이 하나라도 포함되었다는 뜻입니다.
- Accuracy는 검색 시스템이 얼마나 자주 정답을 포함하는지를 측정하며, 정답의 개수나 위치는 고려하지 않습니다.
- 질문 1: [정답, 오답, 오답, 오답, 오답] -> 포함(성공)
- 질문 2: [오답, 오답, 정답, 오답, 오답] -> 포함(성공)
- 질문 3: [오답, 오답, 오답, 오답, 오답] -> 미포함(실패)
- 이때 Accuracy@5 = 2/3 -> 0.667(66.7%) 입니다.

### 2. Precision

- Precision은 상위 검색 결과가 '얼마나 정확히 정답으로 이루어져 있는가?'를 평가합니다.
- Precision@k는 상위 k개의 검색 결과 중 정답이 차지하는 비율입니다.
- 예를들어, Precision@5가 0.20이라는 값은 상위 5개의 결과 중 평균적으로 20%가 정답이라는 뜻입니다.
- Precision은 검색 결과가 불필요한 정보를 얼마나 적게 포함하고 있는지를 보여줍니다.
- 질문 1: [정답, 오답, 오답, 오답, 오답] => Precision@5 = 1/5 = 0.2
- 질문 2: [오답, 정답, 오답, 오답, 오답] => Precision@5 = 1/5 = 0.2
- 질문 3: [오답, 오답, 오답, 오답, 오답] => Precision@5 = 0/5 = 0.0
- 평균 Precision@5 = (0.2 + 0.2 + 0.0) / 3 =0.133(13.3%) 입니다.

### 3. Recall

- Recall은 검색 결과가 얼마나 '포괄적으로' 정답을 포함하고 있는지를 평가합니다.
- Recall@k는 전체 정답 중 검색 결과 상위 k개 안에 포함된 정답의 비율을 나타냅니다.
- Recall은 정답을 놓치지 않고 얼마나 잘 찾아내는지를 보여줍니다.
- 참고로 실습데이터에서는 각 질문당 정답이 하나씩만 있기 때문에 Recall과 Accuracy의 값이 동일합니다.
- 예를 들어, 질문 하나에 정답이 2개 있다고 가정합시다.
- 질문 1: [정답, 정답, 오답, 오답, 오답] => Recall@5 = 2/2 = 1.0
- 질문 2: [정답, 오답, 오답, 오답, 오답] => Recall@5 = 1/2 = 0.5
- 질문 3: [오답, 오답, 오답, 오답, 오답] => Recall@5 = 0/2 = 0.0
- 평균 Recall@5 = (1.0 + 0.5 + 0.0) / 3 = 0.5 (50%) 입니다.

### 4 NDCG(Normalized Discounted Cumulative Gain)

- NDCG는 검색 결과에서 정답이 높은 순위에 배치될수록 높은 점수를 부여합니다.
- 이는 단순히 정답이 포함되었는지를 넘어, 정답의 순위가 사용자에게 얼마나 유용한지를 평가하는 지표입니다.
- NDCG@10이 0.85라는 값은 정답이 대체로 높은 순위에 배치되었음을 의미합니다.
- 질문 1: [정답, 정답, 오답] -> NDCG = 1.0(정답이 모두 상위에 있음)
- 질문 2: [오답, 정답, 오답] -> NDCG는 약 0.63(정답이 두번째 위치에 있음)
- 질문 3: [오답, 오답, 정답] -> NDCG는 약 0.39(정답이 세번째 위치에 있음)
- 평균 NDCG@3 = (1.0+0.63+0.39)/3 = 0.673 입니다.

### 5. MRR(Mean Reciprocal Rank)

- MRR은 정답이 처음 등장한 순위의 역수를 평균한 값입니다.
- 각 질문에 대해 정답이 검색 결과에서 처음 등장한 순위의 역수를 계산한 후, 모든 질문에 대해 그 값을 평균냅니다.
- MRR@10에서 @10은 상위 10개의 검색 결과까지만 고려한다는 의미입니다.
- 정답이 11위 이후에 등장하면 해당 질문은 계산에서 제외되거나 Reciprocal Rank는 0으로 간주됩니다.
- 이 지표는 사용자가 정답을 얼마나 빠르게 찾을 수 있는지를 평가합니다.
- MRR값이 높을수록, 정답이 더 상위 순위에 배치되어 있다는 의미입니다.
- 질문 1:[정답, 오답, 오답, 오답, ...] Reciprocal Rank = 1/1 = 1.0 (정답이 1위에 있음)
- 질문 2:[오답, 정답, 오답, 오답, ...] Reciprocal Rank = 1/2 = 0.5 (정답이 2위에 있음)
- 질문 3:[오답, 오답, 정답, 오답, ...] Reciprocal Rank = 1/3 = 0.33 (정답이 3위에 있음)
- 질문 4:[오답, 오답, 오답, ...] Reciprocal Rank = 0 (정답이 상위 10위 안에 없음)
- 평균 MRR@10 = (1.0 + 5.0 + 0.33 + 0)/4 = 0.458 입니다.

### 6. MAP(Mean Average Precision)

- MAP는 각 정답을 찾을 때마다의 Precision 값을 계산하여 평균을 낸 값으로, 검색 결과의 전반적인 정확도와 일관성을 평가합니다.
- MAP@100에서 @100은 검색 겨로가의 상위 100개 항목까지만 Precision 값을 계산한다는 의미입니다.
- 정답이 101위 이후에 있다면 해당 정답은 계산에서 제외됩니다.
- 이는 평가 범위를 제한함으로써 특정 상위 결과 내에서의 성능을 측정합니다.
- [정답, 정답, 오답, 오답, 정답]
- 첫 번째 정답을 찾았을때: Precision@1 = 1/1 = 1.0
- 두 번째 정답을 찾았을때: Precision@2 = 2/2 = 1.0
- 세 번째 정답을 찾았을때: Precision@5 = 3/5 = 0.6
- MAP@5 = (1.0 + 1.0 + 0.6)/3 = 0.867입니다.
- MAP@100 = 0.818이라는 값은 상위 100개의 검색 결과 내에서 정답을 찾을 때마다 계산된 Precision 값의 평균이 0.818이라는 뜻입니다.
- 이는 시스템이 상위 100개의 결과에서 정답을 얼마나 정확하고 일관되게 제공하는지를 평가하는 지표입니다.

## 3.8 파인튜닝 모델 평가하기

1. 모델은 queries 딕셔너리의 각 질문과 corpus 딕셔너리의 모든 문서를 임베딩 벡터로 변환합니다.
2. 각 질문 벡터와 모든 문서 벡터간의 코사인 유사도 점수를 계산합니다.
3. 각 질문마다 문서들을 유사도 점수가 높은 순서로 정렬합니다.
4. relevant_docs 딕셔너리에 명시된 정답 문서들이 이 정렬된 리스트에서 어떤 순위에 있는지 확인합니다.
5. MRR(Mean Reciprocal Rank), NDCG(Normalized Discounted Cumulative Gain), Percision@k Recall@k등의 검색 성능 평가 지표를 계산합니다.

- 예를 들어 "인공지능이란?" 질문("q0")에 대해 모델이 문서들을 다음과 같이 순위를 매겼다고 가정해봅시다

1. "d0"(인공지능 문서): 0.95점
2. "d2"(자연어 처리 문서): 0.70점
3. "d1"(머신러닝 문서): 0.60점

- relevant_docs 딕셔너리에 "q0": {"d0"}이 있다면, 이는 질문 "q0"의 정답 문서가 "d0"임을 의미합니다.
- 모델이 "d0"을 1위로 정확히 찾았으므로 이 질문에 대해서는 좋은 성능을 보인것입니다.
- 현재의 임베딩 모델은 앞서 설명한 검색 성능 평가 지표에 따라 높은 점수를 얻게 됩니다.

In [19]:
def evaluate_st(dataset, model_id, name, evaluator):
    """
    SentenceTransformer 모델의 검색 성능을 평가하는 함수
    """
    # 평가 결과를 저장할 디렉터리 생성
    os.makedirs("results", exist_ok=True)

    # 평가할 SentenceTransformer 모델 로드
    model = SentenceTransformer(model_id)

    # 모델 평가 수행
    result = evaluator(model)

    # 결과를 DataFrame으로 변환하고 CSV로 저장
    result_df = pd.DataFrame([result]) if isinstance(result, dict) else result
    output_path = f"results/Information-Retrieval_evaluation_{name}_results.csv"
    result_df.to_csv(output_path, index=False)

    return result

- evaluate_st() 함수는 학습하고자 하는 모델과 앞서 구현한 evaluator를 전달하면 해당 모델에 대한 평가 결과를 기록하고 results 디렉터리 안에 CSV파일로 저장합니다.
- 이 CSV 파일에는 상세한 평가 결과가 기록됩니다.
- 다음은 원본 모델과 파인튜닝 모델에 대해 각각 evaluate_st() 함수를 호출하여 평가를 진행하는 코드입니다.

In [20]:
# 원본 모델 평가
original_model_path = "BAAI/bge-m3"
evaluate_st(
    dataset=val_dataset,
    model_id=original_model_path,
    name="original",
    evaluator=evaluator,
)

# 파인튜닝된 모델 평가
finetuned_model_path = "exp_finetune"
evaluate_st(
    dataset=val_dataset,
    model_id=finetuned_model_path,
    name="finetuned",
    evaluator=evaluator,
)

{'cosine_accuracy@1': 0.7962962962962963,
 'cosine_accuracy@3': 0.9444444444444444,
 'cosine_accuracy@5': 0.9629629629629629,
 'cosine_accuracy@10': 1.0,
 'cosine_precision@1': 0.7962962962962963,
 'cosine_precision@3': 0.31481481481481477,
 'cosine_precision@5': 0.1925925925925925,
 'cosine_precision@10': 0.09999999999999996,
 'cosine_recall@1': 0.7962962962962963,
 'cosine_recall@3': 0.9444444444444444,
 'cosine_recall@5': 0.9629629629629629,
 'cosine_recall@10': 1.0,
 'cosine_ndcg@10': 0.9050646715235952,
 'cosine_mrr@10': 0.873971193415638,
 'cosine_map@100': 0.8739711934156378}

- 이제 results 디렉터리에 저장된 결과를 출력하면 다음과 같습니다.

In [21]:
# 결과 비교
df_st_original = pd.read_csv(
    "results/Information-Retrieval_evaluation_original_results.csv"
)
df_st_finetuned = pd.read_csv(
    "results/Information-Retrieval_evaluation_finetuned_results.csv"
)

df_st_original["model"] = "bge-m3"
df_st_finetuned["model"] = "fine_tuned"
df_st_all = pd.concat([df_st_original, df_st_finetuned])
df_st_all = df_st_all.set_index("model")

print("\n모델 성능 비교")
df_st_all

모델 성능 비교

,cosine_accuracy@1,cosine_accuracy@3,cosine_accuracy@5,cosine_accuracy@10,cosine_precision@1,cosine_precision@3,cosine_precision@5,cosine_precision@10,cosine_recall@1,cosine_recall@3,cosine_recall@5,cosine_recall@10,cosine_ndcg@10,cosine_mrr@10,cosine_map@100
model,,,,,,,,,,,,,,,
bge-m3,0.740741,0.907407,0.981481,1.0,0.740741,0.302469,0.196296,0.1,0.740741,0.907407,0.981481,1.0,0.871026,0.829189,0.829189
fine_tuned,0.796296,0.944444,0.962963,1.0,0.796296,0.314815,0.192593,0.1,0.796296,0.944444,0.962963,1.0,0.905065,0.873971,0.873971

- 파인튜닝 정 모델이 1.0으로 이미 최고 점수를 받은 경우에서는 동점을 기록했고, 나머지 모든 평가 지표에서는 파인튜닝 후 모델이 더 높은 성능을 나타냅니다.
- 이는 특정 도메인에 맞게 임베딩 모델을 파인튜닝하면 기존 모델보다 우수한 성능을 얻을 수 있음을 증명합니다.